
-- DML_Aassess.sql
/*

create table tblAassess(
    aassess_seq number primary key,
    graduate_seq number not null references tblGraduate(graduate_seq),
    aassess_name varchar2(500) not null,
    aassess_agood varchar2(20) not null,
    aassess_ask varchar2(4000) not null, 
    aassess_mgood varchar2(20) not null
);
*/

insert into tblAassess values (1, 1, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '관리자 보통이에요', '중');
insert into tblAassess values (2, 2, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '정수기 매우 좋아요', '중');
insert into tblAassess values (3, 3, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '커리큘럼 매우 별로에요', '상');
insert into tblAassess values (4, 4, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '사물함 낫배드', '상');
insert into tblAassess values (5, 5, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '강의실 보통이에요', '하');
insert into tblAassess values (6, 6, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '종이컵 보통이에요', '하');
insert into tblAassess values (7, 7, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '종이컵 별로에요', '중');
insert into tblAassess values (8, 8, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '종이컵 낫배드', '상');
insert into tblAassess values (9, 9, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '관리자 매우 별로에요', '중');
insert into tblAassess values (10, 10, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '사물함 매우 좋아요', '상');
insert into tblAassess values (11, 11, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '사물함 매우 별로에요', '중');
insert into tblAassess values (12, 12, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '커리큘럼 낫배드', '중');
insert into tblAassess values (13, 13, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '수업 매우 별로에요', '중');
insert into tblAassess values (14, 14, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '정수기 보통이에요', '중');
insert into tblAassess values (15, 15, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '관리자 매우 별로에요', '중');
insert into tblAassess values (16, 16, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '수업 낫배드', '하');
insert into tblAassess values (17, 17, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '강의 매우 좋아요', '상');
insert into tblAassess values (18, 18, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '수업 별로에요', '중');
insert into tblAassess values (19, 19, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '시설 매우 별로에요', '상');
insert into tblAassess values (20, 20, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '사물함 매우 좋아요', '중');
insert into tblAassess values (21, 21, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '강의 낫배드', '상');
insert into tblAassess values (22, 22, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '사물함 좋아요', '중');
insert into tblAassess values (23, 23, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '시설 별로에요', '중');
insert into tblAassess values (24, 24, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '수업 보통이에요', '중');
insert into tblAassess values (25, 25, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '수업 좋아요', '하');
insert into tblAassess values (26, 26, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '종이컵 매우 좋아요', '중');
insert into tblAassess values (27, 27, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '동기 매우 별로에요', '하');
insert into tblAassess values (28, 28, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '커리큘럼 매우 좋아요', '상');
insert into tblAassess values (29, 29, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '종이컵 낫배드', '상');
insert into tblAassess values (30, 30, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '강의 매우 좋아요', '중');
insert into tblAassess values (31, 31, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '교통 좋아요', '중');
insert into tblAassess values (32, 32, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '정수기 보통이에요', '하');
insert into tblAassess values (33, 33, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '관리자 좋아요', '중');
insert into tblAassess values (34, 34, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '강의실 낫배드', '중');
insert into tblAassess values (35, 35, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '강의 좋아요', '상');
insert into tblAassess values (36, 36, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '사물함 낫배드', '상');
insert into tblAassess values (37, 37, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '종이컵 매우 별로에요', '상');
insert into tblAassess values (38, 38, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '교통 보통이에요', '상');
insert into tblAassess values (39, 39, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '동기 낫배드', '중');
insert into tblAassess values (40, 40, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '수업 별로에요', '상');
insert into tblAassess values (41, 41, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '커리큘럼 별로에요', '하');
insert into tblAassess values (42, 42, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '강의실 매우 좋아요', '상');
insert into tblAassess values (43, 43, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '종이컵 보통이에요', '하');
insert into tblAassess values (44, 44, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '수업 매우 좋아요', '하');
insert into tblAassess values (45, 45, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '시설 매우 별로에요', '상');
insert into tblAassess values (46, 46, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '종이컵 낫배드', '상');
insert into tblAassess values (47, 47, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '교통 별로에요', '하');
insert into tblAassess values (48, 48, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '강의 매우 별로에요', '상');
insert into tblAassess values (49, 49, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '사물함 별로에요', '하');
insert into tblAassess values (50, 50, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '강의실 별로에요', '상');
insert into tblAassess values (51, 51, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '동기 매우 좋아요', '상');
insert into tblAassess values (52, 52, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '교통 매우 좋아요', '중');
insert into tblAassess values (53, 53, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '종이컵 보통이에요', '하');
insert into tblAassess values (54, 54, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '강의 매우 좋아요', '하');
insert into tblAassess values (55, 55, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '강의 낫배드', '중');
insert into tblAassess values (56, 56, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '동기 낫배드', '상');
insert into tblAassess values (57, 57, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '정수기 보통이에요', '상');
insert into tblAassess values (58, 58, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '정수기 매우 좋아요', '상');
insert into tblAassess values (59, 59, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '강의실 매우 좋아요', '중');
insert into tblAassess values (60, 60, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '수업 보통이에요', '중');
insert into tblAassess values (61, 61, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '교통 매우 좋아요', '중');
insert into tblAassess values (62, 62, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '수업 낫배드', '상');
insert into tblAassess values (63, 63, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '시설 별로에요', '중');
insert into tblAassess values (64, 64, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '강의 보통이에요', '상');
insert into tblAassess values (65, 65, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '정수기 매우 별로에요', '상');
insert into tblAassess values (66, 66, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '동기 낫배드', '하');
insert into tblAassess values (67, 67, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '시설 좋아요', '하');
insert into tblAassess values (68, 68, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '강의 별로에요', '상');
insert into tblAassess values (69, 69, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '종이컵 매우 별로에요', '하');
insert into tblAassess values (70, 70, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '사물함 매우 별로에요', '상');
insert into tblAassess values (71, 71, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '수업 낫배드', '하');
insert into tblAassess values (72, 72, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '사물함 좋아요', '하');
insert into tblAassess values (73, 73, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '관리자 매우 별로에요', '하');
insert into tblAassess values (74, 74, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '강의 별로에요', '상');
insert into tblAassess values (75, 75, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '동기 매우 별로에요', '하');
insert into tblAassess values (76, 76, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '동기 매우 좋아요', '중');
insert into tblAassess values (77, 77, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '관리자 보통이에요', '상');
insert into tblAassess values (78, 78, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '강의 낫배드', '중');
insert into tblAassess values (79, 79, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '수업 낫배드', '상');
insert into tblAassess values (80, 80, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '사물함 낫배드', '상');
insert into tblAassess values (81, 81, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '강의실 별로에요', '하');
insert into tblAassess values (82, 82, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '시설 보통이에요', '하');
insert into tblAassess values (83, 83, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '종이컵 별로에요', '중');
insert into tblAassess values (84, 84, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '정수기 좋아요', '하');
insert into tblAassess values (85, 85, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '수업 별로에요', '상');
insert into tblAassess values (86, 86, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '사물함 매우 별로에요', '하');
insert into tblAassess values (87, 87, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '동기 별로에요', '상');
insert into tblAassess values (88, 88, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '관리자 매우 별로에요', '중');
insert into tblAassess values (89, 89, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '교통 낫배드', '하');
insert into tblAassess values (90, 90, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '사물함 매우 별로에요', '하');
insert into tblAassess values (91, 91, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '동기 별로에요', '상');
insert into tblAassess values (92, 92, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '관리자 별로에요', '상');
insert into tblAassess values (93, 93, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '강의 좋아요', '중');
insert into tblAassess values (94, 94, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '시설 낫배드', '하');
insert into tblAassess values (95, 95, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '종이컵 매우 별로에요', '중');
insert into tblAassess values (96, 96, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '중', '정수기 낫배드', '상');
insert into tblAassess values (97, 97, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '강의실 보통이에요', '하');
insert into tblAassess values (98, 98, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '정수기 매우 좋아요', '하');
insert into tblAassess values (99, 99, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '상', '강의 매우 좋아요', '상');
insert into tblAassess values (100, 100, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', '하', '교통 보통이에요', '중');


insert into tblAassess values (101, 101, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '교통 좋아요', '중');
insert into tblAassess values (102, 102, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '정수기 매우 좋아요', '하');
insert into tblAassess values (103, 103, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '수업 별로에요', '하');
insert into tblAassess values (104, 104, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '동기 보통이에요', '중');
insert into tblAassess values (105, 105, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '강의실 매우 별로에요', '상');
insert into tblAassess values (106, 106, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '수업 보통이에요', '상');
insert into tblAassess values (107, 107, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '관리자 낫배드', '중');
insert into tblAassess values (108, 108, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 매우 별로에요', '하');
insert into tblAassess values (109, 109, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '강의실 보통이에요', '중');
insert into tblAassess values (110, 110, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '교통 매우 별로에요', '하');
insert into tblAassess values (111, 111, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '강의 좋아요', '하');
insert into tblAassess values (112, 112, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '사물함 별로에요', '중');
insert into tblAassess values (113, 113, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '정수기 별로에요', '중');
insert into tblAassess values (114, 114, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '수업 보통이에요', '중');
insert into tblAassess values (115, 115, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '동기 별로에요', '하');
insert into tblAassess values (116, 116, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '종이컵 보통이에요', '상');
insert into tblAassess values (117, 117, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '종이컵 매우 별로에요', '중');
insert into tblAassess values (118, 118, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 매우 좋아요', '하');
insert into tblAassess values (119, 119, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '관리자 낫배드', '중');
insert into tblAassess values (120, 120, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '강의 좋아요', '중');
insert into tblAassess values (121, 121, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 매우 좋아요', '하');
insert into tblAassess values (122, 122, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '정수기 낫배드', '상');
insert into tblAassess values (123, 123, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '수업 보통이에요', '중');
insert into tblAassess values (124, 124, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '교통 매우 좋아요', '하');
insert into tblAassess values (125, 125, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '강의 매우 좋아요', '하');
insert into tblAassess values (126, 126, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '사물함 매우 별로에요', '상');
insert into tblAassess values (127, 127, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '사물함 보통이에요', '상');
insert into tblAassess values (128, 128, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '종이컵 매우 좋아요', '상');
insert into tblAassess values (129, 129, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '정수기 별로에요', '하');
insert into tblAassess values (130, 130, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '사물함 별로에요', '하');
insert into tblAassess values (131, 131, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '강의 매우 별로에요', '중');
insert into tblAassess values (132, 132, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '커리큘럼 매우 별로에요', '하');
insert into tblAassess values (133, 133, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '강의 매우 별로에요', '중');
insert into tblAassess values (134, 134, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '커리큘럼 매우 별로에요', '상');
insert into tblAassess values (135, 135, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '강의 별로에요', '하');
insert into tblAassess values (136, 136, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '관리자 매우 별로에요', '중');
insert into tblAassess values (137, 137, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '강의 좋아요', '중');
insert into tblAassess values (138, 138, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '강의실 낫배드', '중');
insert into tblAassess values (139, 139, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '커리큘럼 낫배드', '상');
insert into tblAassess values (140, 140, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '시설 보통이에요', '중');
insert into tblAassess values (141, 141, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '커리큘럼 낫배드', '하');
insert into tblAassess values (142, 142, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '정수기 좋아요', '상');
insert into tblAassess values (143, 143, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '시설 보통이에요', '상');
insert into tblAassess values (144, 144, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '정수기 매우 좋아요', '하');
insert into tblAassess values (145, 145, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '시설 별로에요', '중');
insert into tblAassess values (146, 146, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '동기 매우 별로에요', '중');
insert into tblAassess values (147, 147, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '정수기 보통이에요', '중');
insert into tblAassess values (148, 148, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '동기 매우 좋아요', '상');
insert into tblAassess values (149, 149, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '동기 좋아요', '중');
insert into tblAassess values (150, 150, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '정수기 낫배드', '상');
insert into tblAassess values (151, 151, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '커리큘럼 낫배드', '중');
insert into tblAassess values (152, 152, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '종이컵 매우 좋아요', '중');
insert into tblAassess values (153, 153, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '강의실 좋아요', '상');
insert into tblAassess values (154, 154, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '관리자 보통이에요', '중');
insert into tblAassess values (155, 155, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '정수기 좋아요', '중');
insert into tblAassess values (156, 156, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '커리큘럼 매우 별로에요', '중');
insert into tblAassess values (157, 157, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '사물함 보통이에요', '중');
insert into tblAassess values (158, 158, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '관리자 낫배드', '하');
insert into tblAassess values (159, 159, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '커리큘럼 매우 좋아요', '하');
insert into tblAassess values (160, 160, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '교통 매우 별로에요', '중');
insert into tblAassess values (161, 161, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '교통 보통이에요', '상');
insert into tblAassess values (162, 162, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '강의 별로에요', '중');
insert into tblAassess values (163, 163, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '동기 매우 좋아요', '중');
insert into tblAassess values (164, 164, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '종이컵 매우 별로에요', '중');
insert into tblAassess values (165, 165, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '동기 별로에요', '상');
insert into tblAassess values (166, 166, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '사물함 매우 별로에요', '하');
insert into tblAassess values (167, 167, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '정수기 좋아요', '하');
insert into tblAassess values (168, 168, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '시설 매우 별로에요', '하');
insert into tblAassess values (169, 169, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '강의실 매우 별로에요', '상');
insert into tblAassess values (170, 170, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '동기 별로에요', '하');
insert into tblAassess values (171, 171, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '시설 매우 좋아요', '상');
insert into tblAassess values (172, 172, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '관리자 좋아요', '하');
insert into tblAassess values (173, 173, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '동기 매우 별로에요', '하');
insert into tblAassess values (174, 174, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 보통이에요', '중');
insert into tblAassess values (175, 175, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '관리자 별로에요', '상');
insert into tblAassess values (176, 176, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '정수기 좋아요', '중');
insert into tblAassess values (177, 177, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '사물함 매우 좋아요', '중');
insert into tblAassess values (178, 178, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '정수기 낫배드', '상');
insert into tblAassess values (179, 179, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '강의실 매우 좋아요', '상');
insert into tblAassess values (180, 180, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '시설 보통이에요', '하');
insert into tblAassess values (181, 181, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '커리큘럼 매우 좋아요', '상');
insert into tblAassess values (182, 182, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '교통 매우 별로에요', '중');
insert into tblAassess values (183, 183, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 좋아요', '상');
insert into tblAassess values (184, 184, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '강의실 보통이에요', '상');
insert into tblAassess values (185, 185, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 낫배드', '중');
insert into tblAassess values (186, 186, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '강의 매우 별로에요', '중');
insert into tblAassess values (187, 187, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '강의 보통이에요', '중');
insert into tblAassess values (188, 188, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '시설 좋아요', '중');
insert into tblAassess values (189, 189, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '관리자 별로에요', '상');
insert into tblAassess values (190, 190, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '중', '사물함 별로에요', '중');
insert into tblAassess values (191, 191, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 좋아요', '상');
insert into tblAassess values (192, 192, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '강의 별로에요', '상');
insert into tblAassess values (193, 193, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '정수기 낫배드', '상');
insert into tblAassess values (194, 194, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 별로에요', '하');
insert into tblAassess values (195, 195, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '동기 매우 별로에요', '중');
insert into tblAassess values (196, 196, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '시설 좋아요', '상');
insert into tblAassess values (197, 197, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '수업 좋아요', '중');
insert into tblAassess values (198, 198, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '하', '교통 낫배드', '상');
insert into tblAassess values (199, 199, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '교통 별로에요', '중');
insert into tblAassess values (200, 200, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', '상', '종이컵 좋아요', '중');


insert into tblAassess values (201, 201, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '시설 좋아요', '상');
insert into tblAassess values (202, 202, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '동기 별로에요', '상');
insert into tblAassess values (203, 203, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '동기 매우 좋아요', '하');
insert into tblAassess values (204, 204, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '교통 매우 별로에요', '상');
insert into tblAassess values (205, 205, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '정수기 좋아요', '중');
insert into tblAassess values (206, 206, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '커리큘럼 매우 별로에요', '상');
insert into tblAassess values (207, 207, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '강의 보통이에요', '중');
insert into tblAassess values (208, 208, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '강의실 낫배드', '하');
insert into tblAassess values (209, 209, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '커리큘럼 매우 별로에요', '중');
insert into tblAassess values (210, 210, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '강의 별로에요', '상');
insert into tblAassess values (211, 211, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '관리자 보통이에요', '하');
insert into tblAassess values (212, 212, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '정수기 좋아요', '중');
insert into tblAassess values (213, 213, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '사물함 매우 좋아요', '하');
insert into tblAassess values (214, 214, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '사물함 매우 별로에요', '하');
insert into tblAassess values (215, 215, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '수업 매우 별로에요', '중');
insert into tblAassess values (216, 216, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '관리자 매우 좋아요', '중');
insert into tblAassess values (217, 217, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '교통 낫배드', '하');
insert into tblAassess values (218, 218, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '강의 매우 별로에요', '중');
insert into tblAassess values (219, 219, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '강의 좋아요', '중');
insert into tblAassess values (220, 220, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '교통 좋아요', '하');
insert into tblAassess values (221, 221, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '커리큘럼 보통이에요', '하');
insert into tblAassess values (222, 222, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '정수기 좋아요', '하');
insert into tblAassess values (223, 223, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '관리자 낫배드', '하');
insert into tblAassess values (224, 224, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '종이컵 보통이에요', '중');
insert into tblAassess values (225, 225, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '동기 보통이에요', '중');
insert into tblAassess values (226, 226, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '동기 별로에요', '상');
insert into tblAassess values (227, 227, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '동기 매우 좋아요', '하');
insert into tblAassess values (228, 228, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '정수기 매우 별로에요', '하');
insert into tblAassess values (229, 229, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '정수기 매우 별로에요', '상');
insert into tblAassess values (230, 230, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '강의 보통이에요', '하');
insert into tblAassess values (231, 231, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '커리큘럼 매우 좋아요', '중');
insert into tblAassess values (232, 232, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '사물함 좋아요', '중');
insert into tblAassess values (233, 233, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '수업 보통이에요', '중');
insert into tblAassess values (234, 234, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '커리큘럼 매우 좋아요', '중');
insert into tblAassess values (235, 235, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '사물함 좋아요', '상');
insert into tblAassess values (236, 236, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '커리큘럼 보통이에요', '하');
insert into tblAassess values (237, 237, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '수업 좋아요', '하');
insert into tblAassess values (238, 238, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '종이컵 낫배드', '상');
insert into tblAassess values (239, 239, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '수업 보통이에요', '중');
insert into tblAassess values (240, 240, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '수업 낫배드', '하');
insert into tblAassess values (241, 241, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '강의 매우 좋아요', '하');
insert into tblAassess values (242, 242, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '사물함 매우 별로에요', '상');
insert into tblAassess values (243, 243, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '사물함 좋아요', '중');
insert into tblAassess values (244, 244, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '동기 좋아요', '하');
insert into tblAassess values (245, 245, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '관리자 좋아요', '상');
insert into tblAassess values (246, 246, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '종이컵 보통이에요', '하');
insert into tblAassess values (247, 247, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '종이컵 별로에요', '하');
insert into tblAassess values (248, 248, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '정수기 좋아요', '하');
insert into tblAassess values (249, 249, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '교통 좋아요', '상');
insert into tblAassess values (250, 250, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '사물함 좋아요', '중');
insert into tblAassess values (251, 251, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '수업 좋아요', '중');
insert into tblAassess values (252, 252, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '관리자 좋아요', '하');
insert into tblAassess values (253, 253, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '사물함 매우 좋아요', '중');
insert into tblAassess values (254, 254, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '관리자 매우 별로에요', '하');
insert into tblAassess values (255, 255, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '관리자 좋아요', '하');
insert into tblAassess values (256, 256, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '강의 매우 좋아요', '하');
insert into tblAassess values (257, 257, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '동기 낫배드', '상');
insert into tblAassess values (258, 258, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '관리자 매우 별로에요', '중');
insert into tblAassess values (259, 259, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '교통 좋아요', '상');
insert into tblAassess values (260, 260, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '시설 좋아요', '상');
insert into tblAassess values (261, 261, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '수업 별로에요', '중');
insert into tblAassess values (262, 262, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '강의실 낫배드', '하');
insert into tblAassess values (263, 263, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '교통 매우 별로에요', '하');
insert into tblAassess values (264, 264, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '교통 매우 좋아요', '중');
insert into tblAassess values (265, 265, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '강의실 보통이에요', '중');
insert into tblAassess values (266, 266, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '커리큘럼 낫배드', '상');
insert into tblAassess values (267, 267, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '종이컵 낫배드', '상');
insert into tblAassess values (268, 268, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '시설 좋아요', '하');
insert into tblAassess values (269, 269, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '교통 매우 좋아요', '중');
insert into tblAassess values (270, 270, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '커리큘럼 별로에요', '하');
insert into tblAassess values (271, 271, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '사물함 별로에요', '중');
insert into tblAassess values (272, 272, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '커리큘럼 매우 별로에요', '중');
insert into tblAassess values (273, 273, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '관리자 낫배드', '하');
insert into tblAassess values (274, 274, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '강의 좋아요', '하');
insert into tblAassess values (275, 275, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '정수기 별로에요', '중');
insert into tblAassess values (276, 276, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '정수기 좋아요', '중');
insert into tblAassess values (277, 277, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '시설 별로에요', '중');
insert into tblAassess values (278, 278, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '종이컵 별로에요', '하');
insert into tblAassess values (279, 279, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '정수기 보통이에요', '하');
insert into tblAassess values (280, 280, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '수업 매우 별로에요', '하');
insert into tblAassess values (281, 281, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '강의 낫배드', '하');
insert into tblAassess values (282, 282, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '종이컵 별로에요', '중');
insert into tblAassess values (283, 283, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '수업 낫배드', '상');
insert into tblAassess values (284, 284, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '교통 매우 별로에요', '중');
insert into tblAassess values (285, 285, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '수업 매우 별로에요', '중');
insert into tblAassess values (286, 286, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '관리자 낫배드', '중');
insert into tblAassess values (287, 287, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '강의실 낫배드', '하');
insert into tblAassess values (288, 288, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '강의 낫배드', '하');
insert into tblAassess values (289, 289, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '교통 보통이에요', '하');
insert into tblAassess values (290, 290, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '수업 좋아요', '중');
insert into tblAassess values (291, 291, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '사물함 매우 좋아요', '중');
insert into tblAassess values (292, 292, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '관리자 매우 별로에요', '하');
insert into tblAassess values (293, 293, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '정수기 별로에요', '상');
insert into tblAassess values (294, 294, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '정수기 좋아요', '상');
insert into tblAassess values (295, 295, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '중', '강의실 좋아요', '상');
insert into tblAassess values (296, 296, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '교통 별로에요', '중');
insert into tblAassess values (297, 297, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '수업 낫배드', '중');
insert into tblAassess values (298, 298, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '하', '사물함 별로에요', '상');
insert into tblAassess values (299, 299, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '관리자 낫배드', '하');
insert into tblAassess values (300, 300, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', '상', '관리자 매우 좋아요', '상');


insert into tblAassess values (301, 301, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '교통 낫배드', '중');
insert into tblAassess values (302, 302, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의 보통이에요', '상');
insert into tblAassess values (303, 303, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의실 낫배드', '하');
insert into tblAassess values (304, 304, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '강의 좋아요', '상');
insert into tblAassess values (305, 305, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '강의실 매우 별로에요', '중');
insert into tblAassess values (306, 306, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의실 좋아요', '하');
insert into tblAassess values (307, 307, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '동기 좋아요', '상');
insert into tblAassess values (308, 308, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '시설 좋아요', '하');
insert into tblAassess values (309, 309, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '정수기 매우 별로에요', '상');
insert into tblAassess values (310, 310, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '종이컵 좋아요', '중');
insert into tblAassess values (311, 311, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '시설 매우 좋아요', '중');
insert into tblAassess values (312, 312, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '강의 매우 좋아요', '하');
insert into tblAassess values (313, 313, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '정수기 낫배드', '상');
insert into tblAassess values (314, 314, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '동기 별로에요', '하');
insert into tblAassess values (315, 315, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '커리큘럼 매우 좋아요', '하');
insert into tblAassess values (316, 316, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '교통 매우 별로에요', '하');
insert into tblAassess values (317, 317, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '시설 보통이에요', '상');
insert into tblAassess values (318, 318, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '관리자 낫배드', '상');
insert into tblAassess values (319, 319, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '수업 보통이에요', '중');
insert into tblAassess values (320, 320, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '교통 별로에요', '상');
insert into tblAassess values (321, 321, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '사물함 낫배드', '중');
insert into tblAassess values (322, 322, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의실 낫배드', '상');
insert into tblAassess values (323, 323, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '종이컵 별로에요', '중');
insert into tblAassess values (324, 324, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '종이컵 좋아요', '상');
insert into tblAassess values (325, 325, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '사물함 별로에요', '상');
insert into tblAassess values (326, 326, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '수업 매우 별로에요', '중');
insert into tblAassess values (327, 327, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '커리큘럼 낫배드', '하');
insert into tblAassess values (328, 328, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의실 매우 좋아요', '중');
insert into tblAassess values (329, 329, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '교통 별로에요', '중');
insert into tblAassess values (330, 330, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '종이컵 매우 별로에요', '중');
insert into tblAassess values (331, 331, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '동기 보통이에요', '상');
insert into tblAassess values (332, 332, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '시설 낫배드', '상');
insert into tblAassess values (333, 333, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '동기 매우 좋아요', '중');
insert into tblAassess values (334, 334, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '시설 낫배드', '중');
insert into tblAassess values (335, 335, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '시설 별로에요', '하');
insert into tblAassess values (336, 336, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '사물함 낫배드', '하');
insert into tblAassess values (337, 337, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '강의실 매우 좋아요', '하');
insert into tblAassess values (338, 338, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '수업 매우 좋아요', '중');
insert into tblAassess values (339, 339, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '커리큘럼 별로에요', '상');
insert into tblAassess values (340, 340, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '시설 보통이에요', '상');
insert into tblAassess values (341, 341, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '커리큘럼 별로에요', '상');
insert into tblAassess values (342, 342, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '강의실 낫배드', '중');
insert into tblAassess values (343, 343, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의실 별로에요', '중');
insert into tblAassess values (344, 344, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '관리자 매우 별로에요', '중');
insert into tblAassess values (345, 345, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '커리큘럼 매우 별로에요', '하');
insert into tblAassess values (346, 346, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '수업 낫배드', '상');
insert into tblAassess values (347, 347, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '커리큘럼 별로에요', '하');
insert into tblAassess values (348, 348, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '관리자 보통이에요', '하');
insert into tblAassess values (349, 349, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '강의 낫배드', '하');
insert into tblAassess values (350, 350, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '수업 별로에요', '중');
insert into tblAassess values (351, 351, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '커리큘럼 매우 별로에요', '중');
insert into tblAassess values (352, 352, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '시설 매우 좋아요', '상');
insert into tblAassess values (353, 353, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '관리자 별로에요', '상');
insert into tblAassess values (354, 354, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '관리자 낫배드', '중');
insert into tblAassess values (355, 355, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '교통 좋아요', '중');
insert into tblAassess values (356, 356, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의 보통이에요', '중');
insert into tblAassess values (357, 357, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '수업 낫배드', '상');
insert into tblAassess values (358, 358, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '커리큘럼 좋아요', '상');
insert into tblAassess values (359, 359, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '수업 좋아요', '하');
insert into tblAassess values (360, 360, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '교통 매우 별로에요', '하');
insert into tblAassess values (361, 361, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '교통 별로에요', '하');
insert into tblAassess values (362, 362, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '수업 매우 좋아요', '상');
insert into tblAassess values (363, 363, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의 좋아요', '하');
insert into tblAassess values (364, 364, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의 매우 별로에요', '상');
insert into tblAassess values (365, 365, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '종이컵 별로에요', '상');
insert into tblAassess values (366, 366, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '시설 좋아요', '하');
insert into tblAassess values (367, 367, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '관리자 별로에요', '상');
insert into tblAassess values (368, 368, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '수업 좋아요', '중');
insert into tblAassess values (369, 369, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '종이컵 낫배드', '중');
insert into tblAassess values (370, 370, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '교통 낫배드', '상');
insert into tblAassess values (371, 371, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '사물함 매우 별로에요', '상');
insert into tblAassess values (372, 372, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '강의실 낫배드', '하');
insert into tblAassess values (373, 373, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '종이컵 좋아요', '하');
insert into tblAassess values (374, 374, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의 별로에요', '중');
insert into tblAassess values (375, 375, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '동기 낫배드', '하');
insert into tblAassess values (376, 376, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '사물함 매우 별로에요', '하');
insert into tblAassess values (377, 377, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '강의 매우 별로에요', '상');
insert into tblAassess values (378, 378, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '시설 매우 좋아요', '중');
insert into tblAassess values (379, 379, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '시설 매우 별로에요', '상');
insert into tblAassess values (380, 380, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '수업 매우 좋아요', '중');
insert into tblAassess values (381, 381, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '사물함 매우 별로에요', '하');
insert into tblAassess values (382, 382, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '종이컵 매우 좋아요', '상');
insert into tblAassess values (383, 383, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '동기 별로에요', '상');
insert into tblAassess values (384, 384, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '커리큘럼 낫배드', '하');
insert into tblAassess values (385, 385, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의실 매우 별로에요', '상');
insert into tblAassess values (386, 386, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '커리큘럼 좋아요', '상');
insert into tblAassess values (387, 387, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '수업 낫배드', '상');
insert into tblAassess values (388, 388, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '수업 좋아요', '하');
insert into tblAassess values (389, 389, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '커리큘럼 보통이에요', '상');
insert into tblAassess values (390, 390, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '시설 별로에요', '중');
insert into tblAassess values (391, 391, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '교통 낫배드', '중');
insert into tblAassess values (392, 392, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '관리자 매우 별로에요', '하');
insert into tblAassess values (393, 393, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '강의 매우 별로에요', '하');
insert into tblAassess values (394, 394, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '커리큘럼 매우 별로에요', '상');
insert into tblAassess values (395, 395, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '사물함 별로에요', '하');
insert into tblAassess values (396, 396, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '강의실 매우 별로에요', '상');
insert into tblAassess values (397, 397, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '정수기 별로에요', '상');
insert into tblAassess values (398, 398, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '하', '교통 매우 별로에요', '중');
insert into tblAassess values (399, 399, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '상', '동기 별로에요', '중');
insert into tblAassess values (400, 400, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', '중', '종이컵 보통이에요', '상');


insert into tblAassess values (401, 401, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '시설 매우 별로에요', '중');
insert into tblAassess values (402, 402, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '교통 매우 좋아요', '하');
insert into tblAassess values (403, 403, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '종이컵 낫배드', '중');
insert into tblAassess values (404, 404, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '강의실 좋아요', '중');
insert into tblAassess values (405, 405, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '교통 매우 별로에요', '상');
insert into tblAassess values (406, 406, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '동기 매우 좋아요', '하');
insert into tblAassess values (407, 407, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '수업 매우 좋아요', '중');
insert into tblAassess values (408, 408, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '강의실 별로에요', '하');
insert into tblAassess values (409, 409, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '교통 좋아요', '중');
insert into tblAassess values (410, 410, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '강의 매우 별로에요', '하');
insert into tblAassess values (411, 411, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '교통 좋아요', '하');
insert into tblAassess values (412, 412, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '강의 보통이에요', '중');
insert into tblAassess values (413, 413, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '강의 낫배드', '상');
insert into tblAassess values (414, 414, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '커리큘럼 낫배드', '하');
insert into tblAassess values (415, 415, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '동기 좋아요', '하');
insert into tblAassess values (416, 416, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '커리큘럼 낫배드', '상');
insert into tblAassess values (417, 417, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '사물함 매우 좋아요', '상');
insert into tblAassess values (418, 418, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '수업 낫배드', '중');
insert into tblAassess values (419, 419, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '커리큘럼 낫배드', '상');
insert into tblAassess values (420, 420, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '교통 매우 별로에요', '중');
insert into tblAassess values (421, 421, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '커리큘럼 좋아요', '중');
insert into tblAassess values (422, 422, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '수업 매우 좋아요', '하');
insert into tblAassess values (423, 423, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '정수기 낫배드', '하');
insert into tblAassess values (424, 424, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '동기 좋아요', '하');
insert into tblAassess values (425, 425, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '교통 보통이에요', '중');
insert into tblAassess values (426, 426, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '수업 별로에요', '중');
insert into tblAassess values (427, 427, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '커리큘럼 매우 별로에요', '하');
insert into tblAassess values (428, 428, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '교통 별로에요', '상');
insert into tblAassess values (429, 429, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '커리큘럼 낫배드', '하');
insert into tblAassess values (430, 430, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '동기 매우 좋아요', '중');
insert into tblAassess values (431, 431, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '관리자 매우 좋아요', '중');
insert into tblAassess values (432, 432, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '시설 보통이에요', '하');
insert into tblAassess values (433, 433, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '시설 매우 별로에요', '중');
insert into tblAassess values (434, 434, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '정수기 보통이에요', '상');
insert into tblAassess values (435, 435, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '관리자 낫배드', '중');
insert into tblAassess values (436, 436, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '종이컵 낫배드', '하');
insert into tblAassess values (437, 437, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '교통 낫배드', '상');
insert into tblAassess values (438, 438, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '관리자 보통이에요', '중');
insert into tblAassess values (439, 439, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '시설 낫배드', '상');
insert into tblAassess values (440, 440, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '시설 낫배드', '중');
insert into tblAassess values (441, 441, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '강의실 별로에요', '상');
insert into tblAassess values (442, 442, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '커리큘럼 좋아요', '중');
insert into tblAassess values (443, 443, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '종이컵 매우 별로에요', '중');
insert into tblAassess values (444, 444, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '정수기 매우 좋아요', '중');
insert into tblAassess values (445, 445, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '교통 매우 좋아요', '하');
insert into tblAassess values (446, 446, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '교통 매우 좋아요', '하');
insert into tblAassess values (447, 447, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '사물함 좋아요', '하');
insert into tblAassess values (448, 448, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '종이컵 낫배드', '중');
insert into tblAassess values (449, 449, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '동기 좋아요', '중');
insert into tblAassess values (450, 450, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '관리자 매우 별로에요', '상');
insert into tblAassess values (451, 451, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '커리큘럼 별로에요', '하');
insert into tblAassess values (452, 452, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '관리자 별로에요', '중');
insert into tblAassess values (453, 453, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '수업 별로에요', '중');
insert into tblAassess values (454, 454, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '시설 매우 별로에요', '하');
insert into tblAassess values (455, 455, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '교통 보통이에요', '하');
insert into tblAassess values (456, 456, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '교통 보통이에요', '하');
insert into tblAassess values (457, 457, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '종이컵 보통이에요', '중');
insert into tblAassess values (458, 458, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '교통 낫배드', '상');
insert into tblAassess values (459, 459, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '강의실 낫배드', '상');
insert into tblAassess values (460, 460, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '사물함 매우 별로에요', '상');
insert into tblAassess values (461, 461, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '커리큘럼 매우 별로에요', '하');
insert into tblAassess values (462, 462, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '강의 매우 좋아요', '상');
insert into tblAassess values (463, 463, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '사물함 낫배드', '하');
insert into tblAassess values (464, 464, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '정수기 별로에요', '중');
insert into tblAassess values (465, 465, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '정수기 보통이에요', '하');
insert into tblAassess values (466, 466, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '정수기 매우 좋아요', '하');
insert into tblAassess values (467, 467, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '동기 좋아요', '상');
insert into tblAassess values (468, 468, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '동기 별로에요', '상');
insert into tblAassess values (469, 469, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '커리큘럼 매우 좋아요', '중');
insert into tblAassess values (470, 470, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '사물함 매우 별로에요', '중');
insert into tblAassess values (471, 471, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '강의실 매우 좋아요', '하');
insert into tblAassess values (472, 472, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '커리큘럼 별로에요', '상');
insert into tblAassess values (473, 473, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '정수기 좋아요', '중');
insert into tblAassess values (474, 474, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '사물함 좋아요', '상');
insert into tblAassess values (475, 475, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '관리자 낫배드', '중');
insert into tblAassess values (476, 476, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '사물함 보통이에요', '중');
insert into tblAassess values (477, 477, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '수업 매우 좋아요', '중');
insert into tblAassess values (478, 478, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '종이컵 보통이에요', '중');
insert into tblAassess values (479, 479, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '시설 매우 별로에요', '상');
insert into tblAassess values (480, 480, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '강의실 좋아요', '상');
insert into tblAassess values (481, 481, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '사물함 좋아요', '상');
insert into tblAassess values (482, 482, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '커리큘럼 보통이에요', '중');
insert into tblAassess values (483, 483, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '종이컵 보통이에요', '하');
insert into tblAassess values (484, 484, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '시설 낫배드', '중');
insert into tblAassess values (485, 485, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '강의실 매우 별로에요', '상');
insert into tblAassess values (486, 486, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '커리큘럼 별로에요', '상');
insert into tblAassess values (487, 487, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '교통 매우 별로에요', '하');
insert into tblAassess values (488, 488, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '커리큘럼 보통이에요', '중');
insert into tblAassess values (489, 489, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '동기 별로에요', '중');
insert into tblAassess values (490, 490, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '시설 낫배드', '상');
insert into tblAassess values (491, 491, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '수업 별로에요', '중');
insert into tblAassess values (492, 492, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '강의실 매우 좋아요', '하');
insert into tblAassess values (493, 493, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '동기 낫배드', '하');
insert into tblAassess values (494, 494, '파이썬으로 시작하는 프로그래밍 첫걸음', '중', '시설 매우 좋아요', '중');
insert into tblAassess values (495, 495, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '정수기 매우 좋아요', '하');
insert into tblAassess values (496, 496, '파이썬으로 시작하는 프로그래밍 첫걸음', '하', '교통 좋아요', '중');
insert into tblAassess values (497, 497, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '정수기 별로에요', '하');
insert into tblAassess values (498, 498, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '사물함 매우 좋아요', '중');
insert into tblAassess values (499, 499, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '종이컵 낫배드', '상');
insert into tblAassess values (500, 500, '파이썬으로 시작하는 프로그래밍 첫걸음', '상', '관리자 낫배드', '하');


insert into tblAassess values (501, 501, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '수업 별로에요', '하');
insert into tblAassess values (502, 502, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '강의 매우 좋아요', '중');
insert into tblAassess values (503, 503, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '동기 낫배드', '상');
insert into tblAassess values (504, 504, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '커리큘럼 별로에요', '중');
insert into tblAassess values (505, 505, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '종이컵 별로에요', '상');
insert into tblAassess values (506, 506, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '수업 낫배드', '중');
insert into tblAassess values (507, 507, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '관리자 보통이에요', '상');
insert into tblAassess values (508, 508, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '강의실 매우 좋아요', '하');
insert into tblAassess values (509, 509, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '관리자 매우 좋아요', '중');
insert into tblAassess values (510, 510, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '정수기 별로에요', '중');
insert into tblAassess values (511, 511, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '강의실 매우 좋아요', '중');
insert into tblAassess values (512, 512, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '동기 좋아요', '상');
insert into tblAassess values (513, 513, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '시설 별로에요', '상');
insert into tblAassess values (514, 514, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '커리큘럼 좋아요', '하');
insert into tblAassess values (515, 515, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '교통 낫배드', '하');
insert into tblAassess values (516, 516, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '강의실 별로에요', '하');
insert into tblAassess values (517, 517, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '사물함 매우 좋아요', '하');
insert into tblAassess values (518, 518, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '정수기 매우 별로에요', '하');
insert into tblAassess values (519, 519, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '정수기 낫배드', '하');
insert into tblAassess values (520, 520, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '강의 별로에요', '중');
insert into tblAassess values (521, 521, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '강의실 별로에요', '중');
insert into tblAassess values (522, 522, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '사물함 별로에요', '하');
insert into tblAassess values (523, 523, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '사물함 보통이에요', '중');
insert into tblAassess values (524, 524, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '교통 낫배드', '하');
insert into tblAassess values (525, 525, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '동기 낫배드', '상');
insert into tblAassess values (526, 526, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '사물함 낫배드', '상');
insert into tblAassess values (527, 527, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '강의실 보통이에요', '하');
insert into tblAassess values (528, 528, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '종이컵 매우 별로에요', '하');
insert into tblAassess values (529, 529, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '시설 매우 좋아요', '중');
insert into tblAassess values (530, 530, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '커리큘럼 낫배드', '상');
insert into tblAassess values (531, 531, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '동기 매우 좋아요', '하');
insert into tblAassess values (532, 532, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '정수기 좋아요', '하');
insert into tblAassess values (533, 533, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '시설 매우 별로에요', '하');
insert into tblAassess values (534, 534, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '사물함 보통이에요', '하');
insert into tblAassess values (535, 535, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '수업 별로에요', '상');
insert into tblAassess values (536, 536, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '커리큘럼 매우 별로에요', '중');
insert into tblAassess values (537, 537, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '시설 보통이에요', '중');
insert into tblAassess values (538, 538, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '커리큘럼 보통이에요', '중');
insert into tblAassess values (539, 539, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '수업 별로에요', '상');
insert into tblAassess values (540, 540, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '종이컵 좋아요', '중');
insert into tblAassess values (541, 541, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '교통 매우 별로에요', '중');
insert into tblAassess values (542, 542, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '동기 좋아요', '중');
insert into tblAassess values (543, 543, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '커리큘럼 낫배드', '하');
insert into tblAassess values (544, 544, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '사물함 낫배드', '하');
insert into tblAassess values (545, 545, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '시설 매우 좋아요', '하');
insert into tblAassess values (546, 546, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '종이컵 낫배드', '중');
insert into tblAassess values (547, 547, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '교통 낫배드', '중');
insert into tblAassess values (548, 548, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '사물함 매우 좋아요', '상');
insert into tblAassess values (549, 549, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '커리큘럼 별로에요', '상');
insert into tblAassess values (550, 550, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '시설 매우 별로에요', '하');
insert into tblAassess values (551, 551, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '커리큘럼 낫배드', '하');
insert into tblAassess values (552, 552, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '관리자 매우 별로에요', '중');
insert into tblAassess values (553, 553, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '시설 낫배드', '중');
insert into tblAassess values (554, 554, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '정수기 별로에요', '상');
insert into tblAassess values (555, 555, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '관리자 매우 좋아요', '중');
insert into tblAassess values (556, 556, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '동기 보통이에요', '하');
insert into tblAassess values (557, 557, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '강의실 보통이에요', '상');
insert into tblAassess values (558, 558, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '정수기 매우 별로에요', '상');
insert into tblAassess values (559, 559, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '시설 매우 좋아요', '하');
insert into tblAassess values (560, 560, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '커리큘럼 매우 별로에요', '상');
insert into tblAassess values (561, 561, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '커리큘럼 좋아요', '하');
insert into tblAassess values (562, 562, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '커리큘럼 낫배드', '중');
insert into tblAassess values (563, 563, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '수업 별로에요', '중');
insert into tblAassess values (564, 564, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '사물함 좋아요', '하');
insert into tblAassess values (565, 565, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '강의 좋아요', '상');
insert into tblAassess values (566, 566, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '시설 낫배드', '중');
insert into tblAassess values (567, 567, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '강의실 매우 좋아요', '상');
insert into tblAassess values (568, 568, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '강의 보통이에요', '상');
insert into tblAassess values (569, 569, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '동기 매우 좋아요', '상');
insert into tblAassess values (570, 570, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '종이컵 별로에요', '중');
insert into tblAassess values (571, 571, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '사물함 보통이에요', '중');
insert into tblAassess values (572, 572, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '사물함 낫배드', '중');
insert into tblAassess values (573, 573, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '동기 좋아요', '하');
insert into tblAassess values (574, 574, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '강의 좋아요', '하');
insert into tblAassess values (575, 575, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '사물함 매우 좋아요', '하');
insert into tblAassess values (576, 576, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '종이컵 매우 별로에요', '상');
insert into tblAassess values (577, 577, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '종이컵 매우 별로에요', '상');
insert into tblAassess values (578, 578, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '수업 매우 좋아요', '상');
insert into tblAassess values (579, 579, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '종이컵 매우 좋아요', '하');
insert into tblAassess values (580, 580, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '커리큘럼 매우 좋아요', '하');
insert into tblAassess values (581, 581, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '강의 좋아요', '중');
insert into tblAassess values (582, 582, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '사물함 매우 별로에요', '하');
insert into tblAassess values (583, 583, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '수업 낫배드', '하');
insert into tblAassess values (584, 584, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '사물함 매우 좋아요', '하');
insert into tblAassess values (585, 585, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '종이컵 별로에요', '하');
insert into tblAassess values (586, 586, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '관리자 별로에요', '하');
insert into tblAassess values (587, 587, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '관리자 매우 별로에요', '중');
insert into tblAassess values (588, 588, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '시설 별로에요', '중');
insert into tblAassess values (589, 589, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '관리자 매우 좋아요', '중');
insert into tblAassess values (590, 590, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '강의실 매우 별로에요', '하');
insert into tblAassess values (591, 591, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '교통 매우 좋아요', '중');
insert into tblAassess values (592, 592, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '정수기 낫배드', '상');
insert into tblAassess values (593, 593, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '교통 좋아요', '중');
insert into tblAassess values (594, 594, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '커리큘럼 별로에요', '하');
insert into tblAassess values (595, 595, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '시설 좋아요', '하');
insert into tblAassess values (596, 596, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '교통 보통이에요', '중');
insert into tblAassess values (597, 597, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '중', '정수기 매우 좋아요', '중');
insert into tblAassess values (598, 598, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '하', '동기 좋아요', '중');
insert into tblAassess values (599, 599, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '수업 매우 좋아요', '하');
insert into tblAassess values (600, 600, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', '상', '커리큘럼 낫배드', '중');
