-- Tassess

-- tblTassess
insert into tblTassess values (1, 'name', graduate_seq, tassess_num, 'tassess_ready', 'tassess_good', 'tassess_ask');

insert into tblTassess values (1, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 1, 4, '중', '상', '필기 감사해요');
insert into tblTassess values (2, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 2, 8, '상', '하', '코딩 감사해요');
insert into tblTassess values (3, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 3, 10, '하', '상', '진도 자세히 설명해주세요.');
insert into tblTassess values (4, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 4, 4, '하', '상', '정보처리기사 도움이 많이 됐어요.');
insert into tblTassess values (5, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 5, 4, '상', '상', '과제 어려워요.');
insert into tblTassess values (6, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 6, 3, '하', '하', 'C# 힘들어요');
insert into tblTassess values (7, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 7, 9, '하', '하', '공부 이해가 잘돼요');
insert into tblTassess values (8, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 8, 1, '상', '중', '강의 천천히 설명해주세요');
insert into tblTassess values (9, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 9, 2, '상', '중', '데이터베이스 늘려주세요.');
insert into tblTassess values (10, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 10, 4, '중', '상', 'C++ 부족해요');
insert into tblTassess values (11, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 11, 9, '중', '중', 'DB 늘려주세요.');
insert into tblTassess values (12, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 12, 5, '상', '하', '프로그래밍 도움이 많이 됐어요.');
insert into tblTassess values (13, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 13, 8, '상', '하', '취업 이해가 잘돼요');
insert into tblTassess values (14, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 14, 5, '상', '하', 'DB 너무 느려요');
insert into tblTassess values (15, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 15, 5, '상', '하', '코딩 너무 느려요');
insert into tblTassess values (16, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 16, 6, '하', '상', '파이썬 자세히 설명해주세요.');
insert into tblTassess values (17, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 17, 4, '상', '하', 'C++ 빨라요');
insert into tblTassess values (18, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 18, 3, '상', '하', '취업 부족해요');
insert into tblTassess values (19, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 19, 3, '상', '상', '자바 도움이 많이 됐어요.');
insert into tblTassess values (20, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 20, 1, '하', '중', 'C언어 힘들어요');
insert into tblTassess values (21, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 21, 1, '상', '중', '공부 시간이 부족해요.');
insert into tblTassess values (22, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 22, 10, '상', '중', '정보처리기사 너무 느려요');
insert into tblTassess values (23, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 23, 5, '상', '상', 'C언어 어려워요.');
insert into tblTassess values (24, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 24, 2, '상', '중', '자료구조 너무 느려요');
insert into tblTassess values (25, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 25, 4, '상', '중', '컴활 빨라요');
insert into tblTassess values (26, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 26, 2, '상', '상', '프로그래밍 천천히 설명해주세요');
insert into tblTassess values (27, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 27, 1, '중', '중', 'MySQL 어려워요.');
insert into tblTassess values (28, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 28, 8, '하', '중', '강의 부족해요');
insert into tblTassess values (29, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 29, 8, '하', '하', '강의 도움이 많이 됐어요.');
insert into tblTassess values (30, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 30, 2, '상', '상', '데이터베이스 부족해요');
insert into tblTassess values (31, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 31, 4, '상', '상', 'HTML 너무 느려요');
insert into tblTassess values (32, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 32, 10, '중', '중', 'C++ 부족해요');
insert into tblTassess values (33, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 33, 3, '중', '중', '데이터베이스 이해가 잘돼요');
insert into tblTassess values (34, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 34, 7, '하', '하', '프로그래밍 감사해요');
insert into tblTassess values (35, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 35, 10, '하', '상', '취업 늘려주세요.');
insert into tblTassess values (36, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 36, 6, '중', '상', 'C언어 힘들어요');
insert into tblTassess values (37, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 37, 6, '중', '중', '자격증 힘들어요');
insert into tblTassess values (38, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 38, 6, '상', '중', '오라클 시간이 부족해요.');
insert into tblTassess values (39, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 39, 4, '하', '중', '과제 힘들어요');
insert into tblTassess values (40, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 40, 9, '하', '하', '네트워크 시간이 부족해요.');
insert into tblTassess values (41, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 41, 1, '하', '상', '코딩 감사해요');
insert into tblTassess values (42, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 42, 8, '하', '하', 'DB 너무 느려요');
insert into tblTassess values (43, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 43, 7, '하', '중', '취업 부족해요');
insert into tblTassess values (44, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 44, 8, '하', '상', '자바 너무 느려요');
insert into tblTassess values (45, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 45, 2, '중', '중', '취업 없애주세요.');
insert into tblTassess values (46, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 46, 9, '상', '중', '공부 힘들어요');
insert into tblTassess values (47, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 47, 8, '중', '상', '자격증 이해가 잘돼요');
insert into tblTassess values (48, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 48, 2, '하', '하', 'SQL 감사해요');
insert into tblTassess values (49, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 49, 2, '중', '하', '강의 없애주세요.');
insert into tblTassess values (50, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 50, 6, '중', '중', '과제 도움이 많이 됐어요.');
insert into tblTassess values (51, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 51, 5, '중', '중', '데이터베이스 너무 느려요');
insert into tblTassess values (52, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 52, 10, '상', '중', '정보처리기사 힘들어요');
insert into tblTassess values (53, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 53, 3, '중', '하', 'SQL 빨라요');
insert into tblTassess values (54, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 54, 8, '하', '중', '네트워크 늘려주세요.');
insert into tblTassess values (55, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 55, 7, '중', '상', 'MySQL 늘려주세요.');
insert into tblTassess values (56, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 56, 8, '하', '상', '취업 늘려주세요.');
insert into tblTassess values (57, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 57, 7, '하', '중', '자격증 감사해요');
insert into tblTassess values (58, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 58, 7, '상', '하', '취업 너무 느려요');
insert into tblTassess values (59, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 59, 2, '하', '하', '프로그래밍 이해가 잘돼요');
insert into tblTassess values (60, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 60, 9, '상', '중', '강의 너무 느려요');
insert into tblTassess values (61, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 61, 4, '하', '하', '자격증 시간이 부족해요.');
insert into tblTassess values (62, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 62, 9, '상', '중', '코딩 감사해요');
insert into tblTassess values (63, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 63, 5, '중', '하', '컴활 감사해요');
insert into tblTassess values (64, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 64, 2, '상', '하', '코딩 없애주세요.');
insert into tblTassess values (65, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 65, 3, '상', '중', '필기 감사해요');
insert into tblTassess values (66, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 66, 2, '상', '중', '자료구조 시간이 부족해요.');
insert into tblTassess values (67, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 67, 6, '하', '상', '데이터베이스 힘들어요');
insert into tblTassess values (68, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 68, 10, '중', '중', '자료구조 천천히 설명해주세요');
insert into tblTassess values (69, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 69, 1, '하', '하', '프로젝트 자세히 설명해주세요.');
insert into tblTassess values (70, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 70, 4, '상', '상', '강의 자세히 설명해주세요.');
insert into tblTassess values (71, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 71, 2, '상', '상', '강의 없애주세요.');
insert into tblTassess values (72, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 72, 9, '상', '상', '쉬는시간 도움이 많이 됐어요.');
insert into tblTassess values (73, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 73, 6, '상', '상', '진도 이해가 잘돼요');
insert into tblTassess values (74, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 74, 10, '상', '하', '오라클 너무 느려요');
insert into tblTassess values (75, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 75, 7, '중', '중', 'SQL 천천히 설명해주세요');
insert into tblTassess values (76, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 76, 1, '중', '상', '자료구조 이해가 잘돼요');
insert into tblTassess values (77, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 77, 5, '중', '중', '네트워크 자세히 설명해주세요.');
insert into tblTassess values (78, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 78, 5, '하', '하', '컴활 부족해요');
insert into tblTassess values (79, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 79, 8, '상', '중', '교재 천천히 설명해주세요');
insert into tblTassess values (80, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 80, 3, '하', '중', '과제 천천히 설명해주세요');
insert into tblTassess values (81, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 81, 5, '하', '상', 'MySQL 천천히 설명해주세요');
insert into tblTassess values (82, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 82, 7, '하', '하', '프로젝트 빨라요');
insert into tblTassess values (83, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 83, 3, '하', '하', '교재 너무 느려요');
insert into tblTassess values (84, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 84, 8, '상', '중', '네트워크 없애주세요.');
insert into tblTassess values (85, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 85, 8, '상', '하', 'MySQL 도움이 많이 됐어요.');
insert into tblTassess values (86, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 86, 10, '상', '상', 'DB 없애주세요.');
insert into tblTassess values (87, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 87, 1, '하', '상', 'C# 시간이 부족해요.');
insert into tblTassess values (88, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 88, 8, '중', '중', 'MySQL 늘려주세요.');
insert into tblTassess values (89, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 89, 7, '상', '중', '필기 없애주세요.');
insert into tblTassess values (90, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 90, 3, '상', '중', '데이터베이스 너무 느려요');
insert into tblTassess values (91, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 91, 6, '하', '중', '자격증 어려워요.');
insert into tblTassess values (92, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 92, 2, '상', '상', '파이썬 늘려주세요.');
insert into tblTassess values (93, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 93, 4, '중', '하', '네트워크 늘려주세요.');
insert into tblTassess values (94, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 94, 5, '하', '중', '네트워크 감사해요');
insert into tblTassess values (95, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 95, 6, '상', '상', 'DB 너무 느려요');
insert into tblTassess values (96, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 96, 8, '상', '하', '필기 없애주세요.');
insert into tblTassess values (97, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 97, 2, '하', '중', '프로그래밍 너무 느려요');
insert into tblTassess values (98, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 98, 7, '하', '상', '코딩 부족해요');
insert into tblTassess values (99, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 99, 9, '상', '하', 'MySQL 어려워요.');
insert into tblTassess values (100, '(디지털컨버젼스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(G)', 100, 4, '중', '중', '공부 빨라요');

insert into tblTassess values (101, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 101, 9, '상', '중', '과제 감사해요');
insert into tblTassess values (102, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 102, 4, '하', '중', 'SQL 늘려주세요.');
insert into tblTassess values (103, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 103, 1, '하', '상', '데이터베이스 없애주세요.');
insert into tblTassess values (104, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 104, 5, '하', '하', '프로그래밍 시간이 부족해요.');
insert into tblTassess values (105, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 105, 6, '하', '중', '정보처리기사 늘려주세요.');
insert into tblTassess values (106, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 106, 1, '상', '하', '진도 자세히 설명해주세요.');
insert into tblTassess values (107, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 107, 6, '중', '하', '자료구조 어려워요.');
insert into tblTassess values (108, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 108, 9, '상', '상', 'SQL 감사해요');
insert into tblTassess values (109, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 109, 6, '상', '중', '공부 빨라요');
insert into tblTassess values (110, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 110, 10, '중', '상', '진도 어려워요.');
insert into tblTassess values (111, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 111, 7, '중', '상', 'C++ 자세히 설명해주세요.');
insert into tblTassess values (112, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 112, 10, '상', '상', '네트워크 늘려주세요.');
insert into tblTassess values (113, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 113, 10, '하', '하', 'C++ 어려워요.');
insert into tblTassess values (114, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 114, 1, '중', '중', '진도 이해가 잘돼요');
insert into tblTassess values (115, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 115, 4, '하', '상', '진도 어려워요.');
insert into tblTassess values (116, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 116, 9, '하', '중', '컴활 없애주세요.');
insert into tblTassess values (117, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 117, 3, '하', '상', 'C++ 도움이 많이 됐어요.');
insert into tblTassess values (118, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 118, 10, '상', '상', '프로젝트 이해가 잘돼요');
insert into tblTassess values (119, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 119, 6, '하', '하', '오라클 빨라요');
insert into tblTassess values (120, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 120, 2, '상', '하', '파이썬 감사해요');
insert into tblTassess values (121, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 121, 4, '상', '중', '자바 도움이 많이 됐어요.');
insert into tblTassess values (122, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 122, 8, '하', '상', '자바 없애주세요.');
insert into tblTassess values (123, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 123, 5, '하', '상', 'DB 감사해요');
insert into tblTassess values (124, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 124, 4, '중', '하', '교재 힘들어요');
insert into tblTassess values (125, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 125, 2, '하', '하', '진도 힘들어요');
insert into tblTassess values (126, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 126, 1, '상', '상', '필기 이해가 잘돼요');
insert into tblTassess values (127, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 127, 2, '중', '상', '프로젝트 늘려주세요.');
insert into tblTassess values (128, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 128, 8, '하', '중', '강의 이해가 잘돼요');
insert into tblTassess values (129, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 129, 1, '하', '상', '필기 어려워요.');
insert into tblTassess values (130, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 130, 9, '중', '중', '교재 없애주세요.');
insert into tblTassess values (131, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 131, 2, '하', '하', '공부 감사해요');
insert into tblTassess values (132, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 132, 5, '상', '하', 'C# 자세히 설명해주세요.');
insert into tblTassess values (133, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 133, 7, '하', '중', '쉬는시간 도움이 많이 됐어요.');
insert into tblTassess values (134, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 134, 10, '하', '상', '필기 부족해요');
insert into tblTassess values (135, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 135, 8, '하', '상', '자격증 이해가 잘돼요');
insert into tblTassess values (136, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 136, 3, '하', '상', '자격증 자세히 설명해주세요.');
insert into tblTassess values (137, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 137, 3, '중', '중', '교재 도움이 많이 됐어요.');
insert into tblTassess values (138, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 138, 5, '하', '하', '교재 너무 느려요');
insert into tblTassess values (139, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 139, 2, '하', '상', '자바 힘들어요');
insert into tblTassess values (140, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 140, 9, '하', '하', '오라클 힘들어요');
insert into tblTassess values (141, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 141, 7, '하', '중', '프로그래밍 자세히 설명해주세요.');
insert into tblTassess values (142, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 142, 10, '중', '중', '데이터베이스 자세히 설명해주세요.');
insert into tblTassess values (143, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 143, 6, '중', '하', '프로젝트 어려워요.');
insert into tblTassess values (144, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 144, 6, '하', '상', '과제 도움이 많이 됐어요.');
insert into tblTassess values (145, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 145, 9, '하', '하', 'C# 힘들어요');
insert into tblTassess values (146, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 146, 8, '하', '상', 'C# 어려워요.');
insert into tblTassess values (147, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 147, 5, '상', '하', '강의 없애주세요.');
insert into tblTassess values (148, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 148, 6, '중', '중', '파이썬 어려워요.');
insert into tblTassess values (149, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 149, 4, '상', '하', '코딩 어려워요.');
insert into tblTassess values (150, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 150, 3, '하', '상', '수업 너무 느려요');
insert into tblTassess values (151, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 151, 1, '상', '중', '데이터베이스 너무 느려요');
insert into tblTassess values (152, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 152, 3, '상', '상', 'C# 시간이 부족해요.');
insert into tblTassess values (153, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 153, 5, '하', '상', '진도 늘려주세요.');
insert into tblTassess values (154, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 154, 9, '상', '상', '필기 너무 느려요');
insert into tblTassess values (155, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 155, 9, '상', '상', '교재 도움이 많이 됐어요.');
insert into tblTassess values (156, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 156, 8, '상', '중', 'MySQL 어려워요.');
insert into tblTassess values (157, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 157, 8, '상', '중', '강의 감사해요');
insert into tblTassess values (158, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 158, 5, '중', '하', '오라클 자세히 설명해주세요.');
insert into tblTassess values (159, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 159, 1, '중', '하', '데이터베이스 어려워요.');
insert into tblTassess values (160, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 160, 2, '상', '중', '수업 천천히 설명해주세요');
insert into tblTassess values (161, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 161, 6, '중', '상', '컴활 너무 느려요');
insert into tblTassess values (162, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 162, 10, '상', '하', 'SQL 이해가 잘돼요');
insert into tblTassess values (163, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 163, 7, '상', '상', 'SQL 도움이 많이 됐어요.');
insert into tblTassess values (164, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 164, 7, '상', '하', 'MySQL 늘려주세요.');
insert into tblTassess values (165, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 165, 10, '상', '하', '교재 감사해요');
insert into tblTassess values (166, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 166, 5, '상', '중', '컴활 감사해요');
insert into tblTassess values (167, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 167, 7, '중', '중', '코딩 도움이 많이 됐어요.');
insert into tblTassess values (168, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 168, 10, '중', '상', '강의 늘려주세요.');
insert into tblTassess values (169, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 169, 10, '상', '하', '진도 빨라요');
insert into tblTassess values (170, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 170, 10, '하', '상', '필기 어려워요.');
insert into tblTassess values (171, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 171, 6, '상', '하', '프로젝트 늘려주세요.');
insert into tblTassess values (172, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 172, 4, '중', '상', 'DB 도움이 많이 됐어요.');
insert into tblTassess values (173, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 173, 6, '하', '중', '필기 자세히 설명해주세요.');
insert into tblTassess values (174, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 174, 3, '하', '상', '교재 이해가 잘돼요');
insert into tblTassess values (175, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 175, 2, '하', '상', 'DB 늘려주세요.');
insert into tblTassess values (176, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 176, 9, '하', '중', '자격증 늘려주세요.');
insert into tblTassess values (177, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 177, 10, '상', '중', '취업 이해가 잘돼요');
insert into tblTassess values (178, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 178, 4, '중', '중', '오라클 늘려주세요.');
insert into tblTassess values (179, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 179, 9, '상', '상', '자격증 자세히 설명해주세요.');
insert into tblTassess values (180, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 180, 2, '하', '하', '교재 부족해요');
insert into tblTassess values (181, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 181, 4, '중', '중', '공부 늘려주세요.');
insert into tblTassess values (182, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 182, 1, '중', '중', '네트워크 감사해요');
insert into tblTassess values (183, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 183, 3, '하', '하', '과제 어려워요.');
insert into tblTassess values (184, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 184, 5, '중', '상', '프로그래밍 감사해요');
insert into tblTassess values (185, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 185, 2, '상', '하', '강의 없애주세요.');
insert into tblTassess values (186, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 186, 2, '중', '하', '데이터베이스 빨라요');
insert into tblTassess values (187, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 187, 3, '하', '중', '프로젝트 힘들어요');
insert into tblTassess values (188, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 188, 5, '상', '상', 'SQL 부족해요');
insert into tblTassess values (189, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 189, 6, '중', '하', '파이썬 어려워요.');
insert into tblTassess values (190, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 190, 7, '상', '하', '수업 없애주세요.');
insert into tblTassess values (191, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 191, 4, '상', '중', '코딩 너무 느려요');
insert into tblTassess values (192, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 192, 1, '상', '중', '데이터베이스 어려워요.');
insert into tblTassess values (193, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 193, 8, '중', '하', '필기 힘들어요');
insert into tblTassess values (194, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 194, 10, '상', '중', '공부 부족해요');
insert into tblTassess values (195, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 195, 2, '하', '하', 'HTML 어려워요.');
insert into tblTassess values (196, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 196, 4, '중', '중', '정보처리기사 감사해요');
insert into tblTassess values (197, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 197, 7, '중', '하', '자료구조 자세히 설명해주세요.');
insert into tblTassess values (198, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 198, 2, '상', '상', '자격증 천천히 설명해주세요');
insert into tblTassess values (199, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 199, 9, '중', '상', '필기 힘들어요');
insert into tblTassess values (200, 'AWS 클라우드를 활용한 Full-Stack 개발자 양성과정', 200, 4, '중', '상', 'HTML 없애주세요.');

insert into tblTassess values (201, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 201, 2, '상', '중', 'DB 시간이 부족해요.');
insert into tblTassess values (202, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 202, 7, '상', '상', '수업 늘려주세요.');
insert into tblTassess values (203, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 203, 3, '하', '중', '오라클 감사해요');
insert into tblTassess values (204, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 204, 5, '상', '상', 'C언어 늘려주세요.');
insert into tblTassess values (205, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 205, 10, '상', '중', '쉬는시간 어려워요.');
insert into tblTassess values (206, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 206, 6, '상', '하', '취업 너무 느려요');
insert into tblTassess values (207, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 207, 9, '상', '상', '쉬는시간 너무 느려요');
insert into tblTassess values (208, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 208, 3, '하', '중', '과제 부족해요');
insert into tblTassess values (209, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 209, 3, '하', '중', '오라클 시간이 부족해요.');
insert into tblTassess values (210, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 210, 5, '중', '상', '필기 없애주세요.');
insert into tblTassess values (211, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 211, 5, '하', '중', '공부 빨라요');
insert into tblTassess values (212, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 212, 9, '하', '중', '자바 어려워요.');
insert into tblTassess values (213, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 213, 5, '중', '중', '자바 천천히 설명해주세요');
insert into tblTassess values (214, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 214, 9, '하', '하', '취업 힘들어요');
insert into tblTassess values (215, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 215, 1, '중', '하', '코딩 빨라요');
insert into tblTassess values (216, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 216, 1, '하', '중', '교재 시간이 부족해요.');
insert into tblTassess values (217, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 217, 10, '중', '하', '자격증 천천히 설명해주세요');
insert into tblTassess values (218, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 218, 3, '상', '하', 'HTML 천천히 설명해주세요');
insert into tblTassess values (219, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 219, 4, '중', '하', '코딩 시간이 부족해요.');
insert into tblTassess values (220, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 220, 8, '하', '하', '오라클 힘들어요');
insert into tblTassess values (221, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 221, 7, '하', '중', '자바 자세히 설명해주세요.');
insert into tblTassess values (222, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 222, 3, '상', '중', '진도 도움이 많이 됐어요.');
insert into tblTassess values (223, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 223, 4, '하', '중', '취업 어려워요.');
insert into tblTassess values (224, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 224, 9, '중', '하', 'DB 없애주세요.');
insert into tblTassess values (225, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 225, 7, '중', '상', 'MySQL 부족해요');
insert into tblTassess values (226, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 226, 5, '중', '하', '필기 너무 느려요');
insert into tblTassess values (227, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 227, 1, '상', '상', '공부 너무 느려요');
insert into tblTassess values (228, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 228, 4, '중', '중', 'DB 빨라요');
insert into tblTassess values (229, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 229, 10, '중', '상', '교재 너무 느려요');
insert into tblTassess values (230, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 230, 10, '중', '중', '프로그래밍 천천히 설명해주세요');
insert into tblTassess values (231, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 231, 6, '상', '상', '강의 자세히 설명해주세요.');
insert into tblTassess values (232, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 232, 10, '중', '상', '취업 자세히 설명해주세요.');
insert into tblTassess values (233, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 233, 7, '중', '중', '과제 없애주세요.');
insert into tblTassess values (234, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 234, 5, '상', '하', '코딩 도움이 많이 됐어요.');
insert into tblTassess values (235, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 235, 1, '상', '하', '취업 자세히 설명해주세요.');
insert into tblTassess values (236, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 236, 6, '하', '상', '네트워크 너무 느려요');
insert into tblTassess values (237, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 237, 2, '중', '중', '프로젝트 없애주세요.');
insert into tblTassess values (238, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 238, 9, '상', '상', '교재 어려워요.');
insert into tblTassess values (239, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 239, 5, '상', '중', '컴활 시간이 부족해요.');
insert into tblTassess values (240, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 240, 7, '하', '하', '컴활 이해가 잘돼요');
insert into tblTassess values (241, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 241, 7, '중', '하', '자격증 늘려주세요.');
insert into tblTassess values (242, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 242, 2, '상', '상', '파이썬 힘들어요');
insert into tblTassess values (243, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 243, 10, '하', '중', '프로젝트 힘들어요');
insert into tblTassess values (244, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 244, 4, '중', '상', '쉬는시간 감사해요');
insert into tblTassess values (245, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 245, 3, '중', '하', '오라클 자세히 설명해주세요.');
insert into tblTassess values (246, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 246, 10, '상', '하', 'HTML 이해가 잘돼요');
insert into tblTassess values (247, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 247, 9, '하', '상', '오라클 천천히 설명해주세요');
insert into tblTassess values (248, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 248, 8, '중', '중', '정보처리기사 어려워요.');
insert into tblTassess values (249, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 249, 5, '상', '상', '자격증 너무 느려요');
insert into tblTassess values (250, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 250, 10, '중', '하', 'SQL 자세히 설명해주세요.');
insert into tblTassess values (251, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 251, 9, '하', '중', '필기 힘들어요');
insert into tblTassess values (252, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 252, 7, '상', '하', 'C언어 이해가 잘돼요');
insert into tblTassess values (253, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 253, 4, '하', '하', '컴활 늘려주세요.');
insert into tblTassess values (254, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 254, 5, '하', '중', '프로그래밍 어려워요.');
insert into tblTassess values (255, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 255, 10, '하', '하', '강의 도움이 많이 됐어요.');
insert into tblTassess values (256, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 256, 8, '하', '하', 'C# 이해가 잘돼요');
insert into tblTassess values (257, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 257, 1, '상', '상', '네트워크 시간이 부족해요.');
insert into tblTassess values (258, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 258, 3, '상', '상', '필기 천천히 설명해주세요');
insert into tblTassess values (259, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 259, 6, '중', '중', '자바 없애주세요.');
insert into tblTassess values (260, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 260, 5, '상', '중', '파이썬 자세히 설명해주세요.');
insert into tblTassess values (261, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 261, 6, '하', '중', '진도 힘들어요');
insert into tblTassess values (262, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 262, 7, '상', '중', '프로젝트 천천히 설명해주세요');
insert into tblTassess values (263, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 263, 5, '하', '하', '진도 천천히 설명해주세요');
insert into tblTassess values (264, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 264, 7, '중', '하', '과제 도움이 많이 됐어요.');
insert into tblTassess values (265, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 265, 5, '하', '중', 'C++ 너무 느려요');
insert into tblTassess values (266, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 266, 9, '상', '중', 'DB 힘들어요');
insert into tblTassess values (267, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 267, 6, '중', '하', '자바 어려워요.');
insert into tblTassess values (268, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 268, 3, '하', '상', '필기 늘려주세요.');
insert into tblTassess values (269, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 269, 6, '하', '상', 'HTML 너무 느려요');
insert into tblTassess values (270, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 270, 5, '중', '상', 'DB 감사해요');
insert into tblTassess values (271, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 271, 9, '중', '하', '네트워크 이해가 잘돼요');
insert into tblTassess values (272, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 272, 6, '중', '하', '코딩 감사해요');
insert into tblTassess values (273, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 273, 9, '하', '하', '쉬는시간 이해가 잘돼요');
insert into tblTassess values (274, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 274, 7, '하', '상', '자바 너무 느려요');
insert into tblTassess values (275, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 275, 9, '상', '중', '정보처리기사 감사해요');
insert into tblTassess values (276, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 276, 7, '하', '하', '공부 부족해요');
insert into tblTassess values (277, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 277, 2, '상', '하', '과제 감사해요');
insert into tblTassess values (278, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 278, 1, '상', '하', '자바 없애주세요.');
insert into tblTassess values (279, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 279, 3, '상', '하', '교재 감사해요');
insert into tblTassess values (280, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 280, 6, '상', '하', '오라클 부족해요');
insert into tblTassess values (281, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 281, 1, '하', '상', 'C++ 너무 느려요');
insert into tblTassess values (282, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 282, 8, '중', '중', '취업 어려워요.');
insert into tblTassess values (283, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 283, 10, '상', '중', '진도 도움이 많이 됐어요.');
insert into tblTassess values (284, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 284, 3, '하', '상', '과제 천천히 설명해주세요');
insert into tblTassess values (285, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 285, 6, '하', '중', '데이터베이스 없애주세요.');
insert into tblTassess values (286, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 286, 9, '중', '하', '필기 자세히 설명해주세요.');
insert into tblTassess values (287, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 287, 4, '상', '중', '데이터베이스 감사해요');
insert into tblTassess values (288, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 288, 2, '상', '중', '정보처리기사 감사해요');
insert into tblTassess values (289, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 289, 1, '하', '하', '과제 자세히 설명해주세요.');
insert into tblTassess values (290, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 290, 5, '상', '하', '자바 이해가 잘돼요');
insert into tblTassess values (291, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 291, 7, '중', '상', '코딩 없애주세요.');
insert into tblTassess values (292, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 292, 6, '중', '하', '정보처리기사 어려워요.');
insert into tblTassess values (293, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 293, 7, '중', '상', '취업 늘려주세요.');
insert into tblTassess values (294, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 294, 3, '중', '하', 'C++ 빨라요');
insert into tblTassess values (295, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 295, 8, '하', '상', '필기 없애주세요.');
insert into tblTassess values (296, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 296, 9, '하', '하', '과제 시간이 부족해요.');
insert into tblTassess values (297, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 297, 3, '하', '중', '자바 이해가 잘돼요');
insert into tblTassess values (298, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 298, 3, '상', '하', '공부 도움이 많이 됐어요.');
insert into tblTassess values (299, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 299, 7, '중', '중', '파이썬 도움이 많이 됐어요.');
insert into tblTassess values (300, '(디지털컨버전스)AWS 클라우드 활용 자바(Java) Full-Stack 개발자 양성 과정(L)', 300, 5, '중', '상', '쉬는시간 자세히 설명해주세요.');

insert into tblTassess values (301, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 301, 2, '하', '중', '오라클 힘들어요');
insert into tblTassess values (302, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 302, 7, '하', '중', 'C# 도움이 많이 됐어요.');
insert into tblTassess values (303, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 303, 3, '중', '중', '공부 없애주세요.');
insert into tblTassess values (304, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 304, 3, '상', '중', '취업 빨라요');
insert into tblTassess values (305, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 305, 9, '상', '하', 'MySQL 자세히 설명해주세요.');
insert into tblTassess values (306, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 306, 1, '하', '상', '공부 시간이 부족해요.');
insert into tblTassess values (307, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 307, 6, '하', '상', 'HTML 너무 느려요');
insert into tblTassess values (308, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 308, 9, '하', '하', 'C++ 부족해요');
insert into tblTassess values (309, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 309, 4, '하', '상', '취업 도움이 많이 됐어요.');
insert into tblTassess values (310, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 310, 4, '하', '중', 'C++ 부족해요');
insert into tblTassess values (311, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 311, 7, '상', '중', '자격증 자세히 설명해주세요.');
insert into tblTassess values (312, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 312, 6, '상', '상', 'MySQL 시간이 부족해요.');
insert into tblTassess values (313, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 313, 5, '중', '상', '자바 자세히 설명해주세요.');
insert into tblTassess values (314, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 314, 5, '중', '중', '프로젝트 자세히 설명해주세요.');
insert into tblTassess values (315, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 315, 10, '중', '상', '네트워크 자세히 설명해주세요.');
insert into tblTassess values (316, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 316, 4, '상', '중', '필기 힘들어요');
insert into tblTassess values (317, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 317, 1, '상', '하', 'HTML 이해가 잘돼요');
insert into tblTassess values (318, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 318, 7, '상', '중', '컴활 빨라요');
insert into tblTassess values (319, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 319, 9, '하', '중', 'C++ 도움이 많이 됐어요.');
insert into tblTassess values (320, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 320, 3, '상', '상', '정보처리기사 부족해요');
insert into tblTassess values (321, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 321, 7, '상', '중', 'C++ 도움이 많이 됐어요.');
insert into tblTassess values (322, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 322, 7, '중', '중', '코딩 빨라요');
insert into tblTassess values (323, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 323, 8, '상', '하', 'C++ 없애주세요.');
insert into tblTassess values (324, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 324, 2, '중', '상', '자료구조 이해가 잘돼요');
insert into tblTassess values (325, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 325, 1, '하', '하', 'C언어 너무 느려요');
insert into tblTassess values (326, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 326, 3, '중', '상', '데이터베이스 늘려주세요.');
insert into tblTassess values (327, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 327, 6, '중', '중', 'C++ 도움이 많이 됐어요.');
insert into tblTassess values (328, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 328, 7, '상', '하', 'DB 이해가 잘돼요');
insert into tblTassess values (329, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 329, 9, '상', '하', '자격증 부족해요');
insert into tblTassess values (330, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 330, 7, '상', '상', '자료구조 감사해요');
insert into tblTassess values (331, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 331, 10, '하', '하', '자료구조 부족해요');
insert into tblTassess values (332, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 332, 1, '중', '중', '진도 빨라요');
insert into tblTassess values (333, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 333, 5, '하', '상', '자바 도움이 많이 됐어요.');
insert into tblTassess values (334, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 334, 5, '중', '상', '자격증 천천히 설명해주세요');
insert into tblTassess values (335, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 335, 1, '하', '하', '자료구조 빨라요');
insert into tblTassess values (336, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 336, 9, '중', '상', '파이썬 이해가 잘돼요');
insert into tblTassess values (337, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 337, 1, '상', '상', 'C# 자세히 설명해주세요.');
insert into tblTassess values (338, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 338, 4, '하', '중', 'C++ 늘려주세요.');
insert into tblTassess values (339, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 339, 5, '하', '중', '파이썬 시간이 부족해요.');
insert into tblTassess values (340, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 340, 5, '상', '상', '필기 어려워요.');
insert into tblTassess values (341, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 341, 6, '중', '상', '자바 자세히 설명해주세요.');
insert into tblTassess values (342, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 342, 1, '하', '중', 'DB 자세히 설명해주세요.');
insert into tblTassess values (343, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 343, 6, '중', '중', '오라클 힘들어요');
insert into tblTassess values (344, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 344, 5, '하', '하', '파이썬 천천히 설명해주세요');
insert into tblTassess values (345, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 345, 5, '상', '중', '과제 도움이 많이 됐어요.');
insert into tblTassess values (346, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 346, 10, '상', '중', '자격증 늘려주세요.');
insert into tblTassess values (347, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 347, 5, '상', '중', '공부 시간이 부족해요.');
insert into tblTassess values (348, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 348, 7, '중', '상', 'C# 자세히 설명해주세요.');
insert into tblTassess values (349, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 349, 2, '중', '중', '취업 감사해요');
insert into tblTassess values (350, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 350, 7, '중', '중', '프로그래밍 도움이 많이 됐어요.');
insert into tblTassess values (351, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 351, 7, '하', '하', '프로젝트 이해가 잘돼요');
insert into tblTassess values (352, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 352, 7, '중', '하', '데이터베이스 감사해요');
insert into tblTassess values (353, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 353, 1, '하', '하', '필기 부족해요');
insert into tblTassess values (354, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 354, 5, '중', '중', '공부 도움이 많이 됐어요.');
insert into tblTassess values (355, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 355, 6, '중', '상', 'C++ 어려워요.');
insert into tblTassess values (356, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 356, 3, '하', '하', '컴활 감사해요');
insert into tblTassess values (357, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 357, 2, '상', '하', 'C++ 도움이 많이 됐어요.');
insert into tblTassess values (358, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 358, 5, '하', '상', '쉬는시간 너무 느려요');
insert into tblTassess values (359, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 359, 5, '상', '하', '강의 어려워요.');
insert into tblTassess values (360, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 360, 4, '하', '하', 'HTML 늘려주세요.');
insert into tblTassess values (361, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 361, 4, '중', '상', 'C# 자세히 설명해주세요.');
insert into tblTassess values (362, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 362, 1, '하', '상', 'SQL 자세히 설명해주세요.');
insert into tblTassess values (363, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 363, 2, '하', '중', '강의 늘려주세요.');
insert into tblTassess values (364, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 364, 9, '하', '하', 'C++ 시간이 부족해요.');
insert into tblTassess values (365, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 365, 9, '중', '하', '공부 늘려주세요.');
insert into tblTassess values (366, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 366, 6, '상', '중', '컴활 감사해요');
insert into tblTassess values (367, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 367, 7, '상', '상', '교재 부족해요');
insert into tblTassess values (368, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 368, 5, '하', '하', 'C++ 자세히 설명해주세요.');
insert into tblTassess values (369, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 369, 2, '하', '상', '교재 도움이 많이 됐어요.');
insert into tblTassess values (370, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 370, 4, '중', '중', '진도 빨라요');
insert into tblTassess values (371, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 371, 3, '하', '하', 'SQL 힘들어요');
insert into tblTassess values (372, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 372, 5, '중', '하', '오라클 없애주세요.');
insert into tblTassess values (373, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 373, 3, '상', '상', 'SQL 도움이 많이 됐어요.');
insert into tblTassess values (374, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 374, 1, '중', '상', '데이터베이스 늘려주세요.');
insert into tblTassess values (375, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 375, 1, '중', '하', '자바 감사해요');
insert into tblTassess values (376, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 376, 1, '중', '하', '교재 부족해요');
insert into tblTassess values (377, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 377, 6, '중', '하', 'SQL 자세히 설명해주세요.');
insert into tblTassess values (378, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 378, 1, '중', '상', '교재 빨라요');
insert into tblTassess values (379, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 379, 8, '상', '상', 'DB 늘려주세요.');
insert into tblTassess values (380, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 380, 1, '중', '상', '데이터베이스 자세히 설명해주세요.');
insert into tblTassess values (381, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 381, 3, '하', '상', '오라클 이해가 잘돼요');
insert into tblTassess values (382, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 382, 9, '중', '중', 'C언어 늘려주세요.');
insert into tblTassess values (383, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 383, 5, '하', '중', 'DB 시간이 부족해요.');
insert into tblTassess values (384, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 384, 5, '상', '상', 'C언어 빨라요');
insert into tblTassess values (385, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 385, 10, '하', '하', '컴활 도움이 많이 됐어요.');
insert into tblTassess values (386, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 386, 2, '상', '하', 'MySQL 어려워요.');
insert into tblTassess values (387, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 387, 1, '중', '상', '자격증 자세히 설명해주세요.');
insert into tblTassess values (388, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 388, 5, '중', '상', '교재 어려워요.');
insert into tblTassess values (389, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 389, 10, '하', '하', '컴활 힘들어요');
insert into tblTassess values (390, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 390, 7, '하', '하', 'C# 어려워요.');
insert into tblTassess values (391, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 391, 2, '하', '하', 'C# 시간이 부족해요.');
insert into tblTassess values (392, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 392, 3, '상', '하', '강의 도움이 많이 됐어요.');
insert into tblTassess values (393, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 393, 3, '상', '상', '데이터베이스 빨라요');
insert into tblTassess values (394, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 394, 8, '중', '상', 'MySQL 너무 느려요');
insert into tblTassess values (395, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 395, 10, '중', '하', '정보처리기사 자세히 설명해주세요.');
insert into tblTassess values (396, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 396, 1, '상', '중', '컴활 부족해요');
insert into tblTassess values (397, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 397, 5, '하', '상', '정보처리기사 어려워요.');
insert into tblTassess values (398, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 398, 10, '중', '상', '프로그래밍 너무 느려요');
insert into tblTassess values (399, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 399, 8, '중', '중', '공부 부족해요');
insert into tblTassess values (400, '(디지털컨버전스)자바(JAVA)기반 공공데이터 융합 개발자 양성과정A13', 400, 8, '하', '중', 'HTML 이해가 잘돼요');

insert into tblTassess values (401, '파이썬으로 시작하는 프로그래밍 첫걸음', 401, 3, '중', '중', '공부 부족해요');
insert into tblTassess values (402, '파이썬으로 시작하는 프로그래밍 첫걸음', 402, 3, '하', '하', '파이썬 빨라요');
insert into tblTassess values (403, '파이썬으로 시작하는 프로그래밍 첫걸음', 403, 10, '하', '하', '코딩 도움이 많이 됐어요.');
insert into tblTassess values (404, '파이썬으로 시작하는 프로그래밍 첫걸음', 404, 5, '하', '상', '네트워크 감사해요');
insert into tblTassess values (405, '파이썬으로 시작하는 프로그래밍 첫걸음', 405, 5, '상', '하', '교재 없애주세요.');
insert into tblTassess values (406, '파이썬으로 시작하는 프로그래밍 첫걸음', 406, 3, '하', '상', '자바 없애주세요.');
insert into tblTassess values (407, '파이썬으로 시작하는 프로그래밍 첫걸음', 407, 7, '상', '중', '쉬는시간 자세히 설명해주세요.');
insert into tblTassess values (408, '파이썬으로 시작하는 프로그래밍 첫걸음', 408, 9, '하', '하', '필기 없애주세요.');
insert into tblTassess values (409, '파이썬으로 시작하는 프로그래밍 첫걸음', 409, 8, '중', '중', '정보처리기사 시간이 부족해요.');
insert into tblTassess values (410, '파이썬으로 시작하는 프로그래밍 첫걸음', 410, 2, '상', '상', '프로그래밍 천천히 설명해주세요');
insert into tblTassess values (411, '파이썬으로 시작하는 프로그래밍 첫걸음', 411, 10, '하', '하', 'C# 너무 느려요');
insert into tblTassess values (412, '파이썬으로 시작하는 프로그래밍 첫걸음', 412, 8, '상', '중', '네트워크 부족해요');
insert into tblTassess values (413, '파이썬으로 시작하는 프로그래밍 첫걸음', 413, 7, '하', '상', '교재 없애주세요.');
insert into tblTassess values (414, '파이썬으로 시작하는 프로그래밍 첫걸음', 414, 1, '중', '상', '프로그래밍 이해가 잘돼요');
insert into tblTassess values (415, '파이썬으로 시작하는 프로그래밍 첫걸음', 415, 6, '중', '중', '과제 없애주세요.');
insert into tblTassess values (416, '파이썬으로 시작하는 프로그래밍 첫걸음', 416, 7, '중', '하', 'DB 빨라요');
insert into tblTassess values (417, '파이썬으로 시작하는 프로그래밍 첫걸음', 417, 1, '상', '중', '프로젝트 어려워요.');
insert into tblTassess values (418, '파이썬으로 시작하는 프로그래밍 첫걸음', 418, 6, '상', '상', '공부 부족해요');
insert into tblTassess values (419, '파이썬으로 시작하는 프로그래밍 첫걸음', 419, 2, '중', '상', 'C언어 늘려주세요.');
insert into tblTassess values (420, '파이썬으로 시작하는 프로그래밍 첫걸음', 420, 2, '중', '중', '공부 부족해요');
insert into tblTassess values (421, '파이썬으로 시작하는 프로그래밍 첫걸음', 421, 9, '상', '중', '쉬는시간 늘려주세요.');
insert into tblTassess values (422, '파이썬으로 시작하는 프로그래밍 첫걸음', 422, 7, '중', '하', '오라클 천천히 설명해주세요');
insert into tblTassess values (423, '파이썬으로 시작하는 프로그래밍 첫걸음', 423, 5, '상', '상', 'C언어 부족해요');
insert into tblTassess values (424, '파이썬으로 시작하는 프로그래밍 첫걸음', 424, 10, '하', '중', '수업 도움이 많이 됐어요.');
insert into tblTassess values (425, '파이썬으로 시작하는 프로그래밍 첫걸음', 425, 5, '상', '하', '자료구조 빨라요');
insert into tblTassess values (426, '파이썬으로 시작하는 프로그래밍 첫걸음', 426, 5, '하', '중', '프로젝트 늘려주세요.');
insert into tblTassess values (427, '파이썬으로 시작하는 프로그래밍 첫걸음', 427, 8, '상', '상', 'DB 빨라요');
insert into tblTassess values (428, '파이썬으로 시작하는 프로그래밍 첫걸음', 428, 5, '상', '중', '자격증 감사해요');
insert into tblTassess values (429, '파이썬으로 시작하는 프로그래밍 첫걸음', 429, 7, '하', '중', '자료구조 어려워요.');
insert into tblTassess values (430, '파이썬으로 시작하는 프로그래밍 첫걸음', 430, 4, '상', '하', '네트워크 이해가 잘돼요');
insert into tblTassess values (431, '파이썬으로 시작하는 프로그래밍 첫걸음', 431, 5, '하', '중', '진도 시간이 부족해요.');
insert into tblTassess values (432, '파이썬으로 시작하는 프로그래밍 첫걸음', 432, 6, '중', '하', '자격증 너무 느려요');
insert into tblTassess values (433, '파이썬으로 시작하는 프로그래밍 첫걸음', 433, 2, '상', '중', '파이썬 힘들어요');
insert into tblTassess values (434, '파이썬으로 시작하는 프로그래밍 첫걸음', 434, 3, '하', '중', '정보처리기사 이해가 잘돼요');
insert into tblTassess values (435, '파이썬으로 시작하는 프로그래밍 첫걸음', 435, 10, '중', '중', 'C# 시간이 부족해요.');
insert into tblTassess values (436, '파이썬으로 시작하는 프로그래밍 첫걸음', 436, 10, '하', '상', '쉬는시간 감사해요');
insert into tblTassess values (437, '파이썬으로 시작하는 프로그래밍 첫걸음', 437, 7, '중', '하', 'SQL 늘려주세요.');
insert into tblTassess values (438, '파이썬으로 시작하는 프로그래밍 첫걸음', 438, 10, '상', '상', '프로젝트 늘려주세요.');
insert into tblTassess values (439, '파이썬으로 시작하는 프로그래밍 첫걸음', 439, 6, '상', '중', '자격증 천천히 설명해주세요');
insert into tblTassess values (440, '파이썬으로 시작하는 프로그래밍 첫걸음', 440, 7, '상', '중', '쉬는시간 감사해요');
insert into tblTassess values (441, '파이썬으로 시작하는 프로그래밍 첫걸음', 441, 8, '하', '상', '파이썬 이해가 잘돼요');
insert into tblTassess values (442, '파이썬으로 시작하는 프로그래밍 첫걸음', 442, 1, '상', '하', '강의 감사해요');
insert into tblTassess values (443, '파이썬으로 시작하는 프로그래밍 첫걸음', 443, 3, '하', '중', 'SQL 빨라요');
insert into tblTassess values (444, '파이썬으로 시작하는 프로그래밍 첫걸음', 444, 9, '중', '상', '취업 너무 느려요');
insert into tblTassess values (445, '파이썬으로 시작하는 프로그래밍 첫걸음', 445, 8, '상', '상', 'HTML 빨라요');
insert into tblTassess values (446, '파이썬으로 시작하는 프로그래밍 첫걸음', 446, 6, '중', '상', '데이터베이스 없애주세요.');
insert into tblTassess values (447, '파이썬으로 시작하는 프로그래밍 첫걸음', 447, 9, '중', '상', 'DB 너무 느려요');
insert into tblTassess values (448, '파이썬으로 시작하는 프로그래밍 첫걸음', 448, 3, '상', '하', '오라클 감사해요');
insert into tblTassess values (449, '파이썬으로 시작하는 프로그래밍 첫걸음', 449, 1, '하', '상', '정보처리기사 천천히 설명해주세요');
insert into tblTassess values (450, '파이썬으로 시작하는 프로그래밍 첫걸음', 450, 4, '하', '중', '정보처리기사 늘려주세요.');
insert into tblTassess values (451, '파이썬으로 시작하는 프로그래밍 첫걸음', 451, 10, '중', '하', '진도 이해가 잘돼요');
insert into tblTassess values (452, '파이썬으로 시작하는 프로그래밍 첫걸음', 452, 4, '하', '상', '자료구조 없애주세요.');
insert into tblTassess values (453, '파이썬으로 시작하는 프로그래밍 첫걸음', 453, 2, '하', '하', '자바 힘들어요');
insert into tblTassess values (454, '파이썬으로 시작하는 프로그래밍 첫걸음', 454, 7, '중', '하', '필기 시간이 부족해요.');
insert into tblTassess values (455, '파이썬으로 시작하는 프로그래밍 첫걸음', 455, 2, '상', '상', '과제 감사해요');
insert into tblTassess values (456, '파이썬으로 시작하는 프로그래밍 첫걸음', 456, 1, '중', '상', '컴활 빨라요');
insert into tblTassess values (457, '파이썬으로 시작하는 프로그래밍 첫걸음', 457, 5, '상', '중', '자격증 시간이 부족해요.');
insert into tblTassess values (458, '파이썬으로 시작하는 프로그래밍 첫걸음', 458, 9, '상', '중', '강의 빨라요');
insert into tblTassess values (459, '파이썬으로 시작하는 프로그래밍 첫걸음', 459, 4, '하', '하', 'HTML 어려워요.');
insert into tblTassess values (460, '파이썬으로 시작하는 프로그래밍 첫걸음', 460, 4, '하', '중', '파이썬 천천히 설명해주세요');
insert into tblTassess values (461, '파이썬으로 시작하는 프로그래밍 첫걸음', 461, 3, '하', '하', 'C언어 도움이 많이 됐어요.');
insert into tblTassess values (462, '파이썬으로 시작하는 프로그래밍 첫걸음', 462, 8, '중', '상', '자바 너무 느려요');
insert into tblTassess values (463, '파이썬으로 시작하는 프로그래밍 첫걸음', 463, 6, '하', '상', '자바 천천히 설명해주세요');
insert into tblTassess values (464, '파이썬으로 시작하는 프로그래밍 첫걸음', 464, 6, '하', '중', '쉬는시간 이해가 잘돼요');
insert into tblTassess values (465, '파이썬으로 시작하는 프로그래밍 첫걸음', 465, 6, '하', '하', 'C# 힘들어요');
insert into tblTassess values (466, '파이썬으로 시작하는 프로그래밍 첫걸음', 466, 5, '하', '하', '취업 늘려주세요.');
insert into tblTassess values (467, '파이썬으로 시작하는 프로그래밍 첫걸음', 467, 2, '상', '하', '파이썬 도움이 많이 됐어요.');
insert into tblTassess values (468, '파이썬으로 시작하는 프로그래밍 첫걸음', 468, 10, '중', '상', '자료구조 시간이 부족해요.');
insert into tblTassess values (469, '파이썬으로 시작하는 프로그래밍 첫걸음', 469, 6, '상', '상', '강의 부족해요');
insert into tblTassess values (470, '파이썬으로 시작하는 프로그래밍 첫걸음', 470, 8, '하', '하', '자격증 없애주세요.');
insert into tblTassess values (471, '파이썬으로 시작하는 프로그래밍 첫걸음', 471, 4, '중', '중', '프로그래밍 너무 느려요');
insert into tblTassess values (472, '파이썬으로 시작하는 프로그래밍 첫걸음', 472, 2, '상', '상', '컴활 부족해요');
insert into tblTassess values (473, '파이썬으로 시작하는 프로그래밍 첫걸음', 473, 9, '중', '하', '네트워크 어려워요.');
insert into tblTassess values (474, '파이썬으로 시작하는 프로그래밍 첫걸음', 474, 9, '상', '중', '자료구조 없애주세요.');
insert into tblTassess values (475, '파이썬으로 시작하는 프로그래밍 첫걸음', 475, 8, '상', '하', 'SQL 감사해요');
insert into tblTassess values (476, '파이썬으로 시작하는 프로그래밍 첫걸음', 476, 6, '하', '상', '자료구조 빨라요');
insert into tblTassess values (477, '파이썬으로 시작하는 프로그래밍 첫걸음', 477, 10, '상', '하', 'C언어 힘들어요');
insert into tblTassess values (478, '파이썬으로 시작하는 프로그래밍 첫걸음', 478, 2, '하', '상', '파이썬 자세히 설명해주세요.');
insert into tblTassess values (479, '파이썬으로 시작하는 프로그래밍 첫걸음', 479, 2, '하', '중', '데이터베이스 자세히 설명해주세요.');
insert into tblTassess values (480, '파이썬으로 시작하는 프로그래밍 첫걸음', 480, 10, '상', '중', '진도 없애주세요.');
insert into tblTassess values (481, '파이썬으로 시작하는 프로그래밍 첫걸음', 481, 4, '중', '하', '오라클 천천히 설명해주세요');
insert into tblTassess values (482, '파이썬으로 시작하는 프로그래밍 첫걸음', 482, 6, '하', '상', '프로그래밍 도움이 많이 됐어요.');
insert into tblTassess values (483, '파이썬으로 시작하는 프로그래밍 첫걸음', 483, 1, '하', '하', 'C언어 이해가 잘돼요');
insert into tblTassess values (484, '파이썬으로 시작하는 프로그래밍 첫걸음', 484, 5, '중', '상', '네트워크 빨라요');
insert into tblTassess values (485, '파이썬으로 시작하는 프로그래밍 첫걸음', 485, 1, '중', '중', 'DB 늘려주세요.');
insert into tblTassess values (486, '파이썬으로 시작하는 프로그래밍 첫걸음', 486, 10, '하', '상', '프로젝트 너무 느려요');
insert into tblTassess values (487, '파이썬으로 시작하는 프로그래밍 첫걸음', 487, 3, '상', '중', '교재 자세히 설명해주세요.');
insert into tblTassess values (488, '파이썬으로 시작하는 프로그래밍 첫걸음', 488, 9, '상', '중', 'HTML 부족해요');
insert into tblTassess values (489, '파이썬으로 시작하는 프로그래밍 첫걸음', 489, 1, '중', '상', '자료구조 도움이 많이 됐어요.');
insert into tblTassess values (490, '파이썬으로 시작하는 프로그래밍 첫걸음', 490, 5, '상', '상', 'HTML 너무 느려요');
insert into tblTassess values (491, '파이썬으로 시작하는 프로그래밍 첫걸음', 491, 1, '하', '상', '수업 너무 느려요');
insert into tblTassess values (492, '파이썬으로 시작하는 프로그래밍 첫걸음', 492, 6, '상', '상', 'MySQL 늘려주세요.');
insert into tblTassess values (493, '파이썬으로 시작하는 프로그래밍 첫걸음', 493, 3, '상', '하', 'MySQL 늘려주세요.');
insert into tblTassess values (494, '파이썬으로 시작하는 프로그래밍 첫걸음', 494, 3, '상', '상', '파이썬 빨라요');
insert into tblTassess values (495, '파이썬으로 시작하는 프로그래밍 첫걸음', 495, 4, '하', '하', '정보처리기사 빨라요');
insert into tblTassess values (496, '파이썬으로 시작하는 프로그래밍 첫걸음', 496, 9, '상', '중', '쉬는시간 도움이 많이 됐어요.');
insert into tblTassess values (497, '파이썬으로 시작하는 프로그래밍 첫걸음', 497, 8, '상', '상', '프로그래밍 없애주세요.');
insert into tblTassess values (498, '파이썬으로 시작하는 프로그래밍 첫걸음', 498, 9, '중', '하', '자바 부족해요');
insert into tblTassess values (499, '파이썬으로 시작하는 프로그래밍 첫걸음', 499, 10, '하', '하', '수업 이해가 잘돼요');
insert into tblTassess values (500, '파이썬으로 시작하는 프로그래밍 첫걸음', 500, 7, '하', '중', '쉬는시간 이해가 잘돼요');

insert into tblTassess values (501, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 501, 10, '중', '중', '공부 감사해요');
insert into tblTassess values (502, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 502, 9, '중', '상', '필기 감사해요');
insert into tblTassess values (503, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 503, 2, '중', '하', '공부 천천히 설명해주세요');
insert into tblTassess values (504, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 504, 5, '하', '중', '자격증 이해가 잘돼요');
insert into tblTassess values (505, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 505, 8, '중', '중', '파이썬 부족해요');
insert into tblTassess values (506, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 506, 4, '중', '하', '취업 늘려주세요.');
insert into tblTassess values (507, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 507, 9, '상', '하', 'C# 어려워요.');
insert into tblTassess values (508, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 508, 1, '상', '중', '컴활 어려워요.');
insert into tblTassess values (509, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 509, 5, '중', '하', '네트워크 빨라요');
insert into tblTassess values (510, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 510, 1, '상', '하', '파이썬 빨라요');
insert into tblTassess values (511, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 511, 6, '상', '상', '자료구조 어려워요.');
insert into tblTassess values (512, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 512, 10, '하', '상', '정보처리기사 없애주세요.');
insert into tblTassess values (513, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 513, 7, '상', '상', 'C# 이해가 잘돼요');
insert into tblTassess values (514, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 514, 4, '상', '하', '교재 이해가 잘돼요');
insert into tblTassess values (515, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 515, 4, '상', '중', 'HTML 도움이 많이 됐어요.');
insert into tblTassess values (516, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 516, 5, '하', '중', '네트워크 없애주세요.');
insert into tblTassess values (517, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 517, 8, '중', '상', '프로젝트 빨라요');
insert into tblTassess values (518, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 518, 7, '상', '중', 'MySQL 자세히 설명해주세요.');
insert into tblTassess values (519, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 519, 3, '중', '중', '자료구조 자세히 설명해주세요.');
insert into tblTassess values (520, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 520, 5, '하', '중', '네트워크 없애주세요.');
insert into tblTassess values (521, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 521, 6, '상', '중', '데이터베이스 너무 느려요');
insert into tblTassess values (522, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 522, 3, '하', '하', '데이터베이스 천천히 설명해주세요');
insert into tblTassess values (523, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 523, 8, '상', '중', '코딩 천천히 설명해주세요');
insert into tblTassess values (524, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 524, 6, '중', '하', 'DB 힘들어요');
insert into tblTassess values (525, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 525, 1, '중', '하', '자격증 자세히 설명해주세요.');
insert into tblTassess values (526, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 526, 10, '상', '하', '교재 시간이 부족해요.');
insert into tblTassess values (527, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 527, 5, '상', '중', 'C언어 힘들어요');
insert into tblTassess values (528, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 528, 8, '하', '하', '정보처리기사 감사해요');
insert into tblTassess values (529, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 529, 9, '하', '중', '진도 빨라요');
insert into tblTassess values (530, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 530, 8, '상', '중', '진도 힘들어요');
insert into tblTassess values (531, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 531, 9, '하', '중', '공부 빨라요');
insert into tblTassess values (532, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 532, 4, '중', '하', '컴활 없애주세요.');
insert into tblTassess values (533, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 533, 3, '하', '상', '교재 없애주세요.');
insert into tblTassess values (534, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 534, 10, '상', '중', 'DB 너무 느려요');
insert into tblTassess values (535, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 535, 5, '중', '상', 'DB 감사해요');
insert into tblTassess values (536, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 536, 9, '중', '중', '자바 힘들어요');
insert into tblTassess values (537, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 537, 7, '중', '하', 'C++ 자세히 설명해주세요.');
insert into tblTassess values (538, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 538, 1, '상', '중', 'C++ 감사해요');
insert into tblTassess values (539, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 539, 3, '중', '하', '네트워크 어려워요.');
insert into tblTassess values (540, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 540, 8, '하', '하', '강의 천천히 설명해주세요');
insert into tblTassess values (541, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 541, 2, '중', '중', '코딩 어려워요.');
insert into tblTassess values (542, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 542, 6, '상', '중', '필기 부족해요');
insert into tblTassess values (543, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 543, 9, '중', '중', '자격증 부족해요');
insert into tblTassess values (544, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 544, 10, '중', '하', '데이터베이스 부족해요');
insert into tblTassess values (545, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 545, 3, '중', '하', '자바 자세히 설명해주세요.');
insert into tblTassess values (546, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 546, 6, '상', '하', 'MySQL 어려워요.');
insert into tblTassess values (547, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 547, 10, '하', '하', '필기 자세히 설명해주세요.');
insert into tblTassess values (548, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 548, 3, '상', '상', '코딩 시간이 부족해요.');
insert into tblTassess values (549, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 549, 8, '상', '상', 'DB 어려워요.');
insert into tblTassess values (550, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 550, 1, '중', '상', '필기 빨라요');
insert into tblTassess values (551, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 551, 5, '상', '하', 'SQL 빨라요');
insert into tblTassess values (552, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 552, 5, '중', '상', '자바 자세히 설명해주세요.');
insert into tblTassess values (553, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 553, 3, '하', '하', '네트워크 이해가 잘돼요');
insert into tblTassess values (554, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 554, 9, '중', '중', '취업 늘려주세요.');
insert into tblTassess values (555, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 555, 6, '상', '하', '공부 늘려주세요.');
insert into tblTassess values (556, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 556, 6, '하', '중', '과제 천천히 설명해주세요');
insert into tblTassess values (557, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 557, 2, '하', '중', 'MySQL 자세히 설명해주세요.');
insert into tblTassess values (558, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 558, 7, '하', '하', '자료구조 시간이 부족해요.');
insert into tblTassess values (559, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 559, 5, '상', '하', 'DB 이해가 잘돼요');
insert into tblTassess values (560, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 560, 8, '중', '상', 'MySQL 너무 느려요');
insert into tblTassess values (561, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 561, 10, '상', '하', '강의 힘들어요');
insert into tblTassess values (562, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 562, 8, '중', '상', 'MySQL 부족해요');
insert into tblTassess values (563, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 563, 10, '상', '중', '진도 힘들어요');
insert into tblTassess values (564, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 564, 10, '상', '중', '프로그래밍 천천히 설명해주세요');
insert into tblTassess values (565, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 565, 6, '중', '상', 'MySQL 힘들어요');
insert into tblTassess values (566, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 566, 5, '하', '하', 'DB 힘들어요');
insert into tblTassess values (567, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 567, 3, '하', '하', '네트워크 자세히 설명해주세요.');
insert into tblTassess values (568, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 568, 5, '상', '하', '진도 도움이 많이 됐어요.');
insert into tblTassess values (569, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 569, 5, '중', '상', '과제 없애주세요.');
insert into tblTassess values (570, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 570, 1, '중', '하', 'C# 이해가 잘돼요');
insert into tblTassess values (571, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 571, 6, '상', '상', '공부 늘려주세요.');
insert into tblTassess values (572, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 572, 6, '하', '상', 'HTML 어려워요.');
insert into tblTassess values (573, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 573, 10, '상', '상', 'C언어 빨라요');
insert into tblTassess values (574, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 574, 1, '중', '상', 'MySQL 천천히 설명해주세요');
insert into tblTassess values (575, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 575, 3, '하', '하', 'MySQL 이해가 잘돼요');
insert into tblTassess values (576, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 576, 1, '상', '중', '수업 도움이 많이 됐어요.');
insert into tblTassess values (577, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 577, 8, '상', '하', '공부 감사해요');
insert into tblTassess values (578, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 578, 1, '하', '상', '자바 이해가 잘돼요');
insert into tblTassess values (579, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 579, 1, '상', '중', '프로그래밍 어려워요.');
insert into tblTassess values (580, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 580, 8, '하', '중', '자바 어려워요.');
insert into tblTassess values (581, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 581, 10, '중', '중', '오라클 빨라요');
insert into tblTassess values (582, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 582, 10, '하', '상', '강의 감사해요');
insert into tblTassess values (583, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 583, 7, '상', '하', 'C# 빨라요');
insert into tblTassess values (584, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 584, 4, '중', '상', '취업 없애주세요.');
insert into tblTassess values (585, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 585, 10, '하', '하', '자바 힘들어요');
insert into tblTassess values (586, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 586, 8, '하', '하', 'C# 없애주세요.');
insert into tblTassess values (587, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 587, 1, '상', '하', '쉬는시간 없애주세요.');
insert into tblTassess values (588, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 588, 8, '상', '중', 'HTML 어려워요.');
insert into tblTassess values (589, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 589, 10, '상', '중', '교재 천천히 설명해주세요');
insert into tblTassess values (590, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 590, 1, '하', '중', '쉬는시간 늘려주세요.');
insert into tblTassess values (591, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 591, 6, '하', '상', '수업 시간이 부족해요.');
insert into tblTassess values (592, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 592, 5, '하', '상', 'MySQL 늘려주세요.');
insert into tblTassess values (593, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 593, 10, '중', '중', 'C++ 감사해요');
insert into tblTassess values (594, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 594, 1, '중', '하', '진도 감사해요');
insert into tblTassess values (595, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 595, 9, '하', '상', '강의 천천히 설명해주세요');
insert into tblTassess values (596, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 596, 4, '하', '하', 'MySQL 부족해요');
insert into tblTassess values (597, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 597, 4, '중', '하', '수업 감사해요');
insert into tblTassess values (598, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 598, 4, '상', '중', '자격증 빨라요');
insert into tblTassess values (599, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 599, 3, '하', '하', '공부 천천히 설명해주세요');
insert into tblTassess values (600, '(스마트웹, 콘텐츠개발)반응형 UI/UX 웹콘텐츠 개발자 양성과정A7', 600, 8, '상', '중', '공부 어려워요.');

